docs/resources/rds_instance.md, duplocloud/resource_duplo_rds_instance.go, duplosdk/rds_instance.go
- Delete protection support for rds instance.
- API update delete protection is called after updating state from create API response. Because we need DB identifier for updating delete protection settings. This identifier is computed from the backend.
=> Delete protection support for rds instance.

duplocloud/resource_duplo_k8_config_map.go, duplocloud/resource_duplo_lbconfigs.go, duplocloud/resource_duplo_service.go, duplosdk/duplo_lbconfigs.go, duplosdk/duplo_service.go
- TF provider should not show diffs for empty k8s configmap.
- Error when service is manually deleted by the user and destroyed from terraform, it should pass tf destroy even if the resource is deleted manually from Duplo portal.
=> TF provider should not show diffs for empty k8s configmap.

duplocloud/resource_duplo_service.go
- Replica should not be a mandatory attribute for the services when ASG is set for the service.
=> Replica should not be a mandatory attribute for the services when ASG is set for the service.

docs/resources/duplo_service.md, duplocloud/resource_duplo_gcp_cloud_function.go, duplocloud/resource_duplo_service.go, duplosdk/tenant_gcp_cloud_resources.go
- GCP Cloud function trigger URL missing issue fixed.
- resource duplocloud_duplo_service: replicas: ConflictsWith cannot be set with Required fixed.
=> GCP Cloud function trigger url missing issue fixed.

docs/data-sources/duplo_service.md, docs/data-sources/duplo_services.md, docs/resources/duplo_service.md, docs/resources/rds_instance.md, duplocloud/data_source_duplo_service.go, duplocloud/resource_duplo_ecs_service.go, duplocloud/resource_duplo_rds_instance.go, duplocloud/resource_duplo_service.go, duplocloud/resource_duplo_tenant.go, duplosdk/rds_instance.go
- DaemonSet support is added in duplo service.
- Logging support is added in rds instance.
- Multi az support is added for rds.
- tenant creation wait time is increased from 45 sec to 2 min to avoid issues we observed in kloudspot, Like - Invalid IAM instance profile Name.
- Wait 40 seconds after destroying an ECS service to avoid race conditions.
=> DaemonSet, RDS MultiAZ and RDS logging support is added.

duplocloud/resource_duplo_lbconfigs.go
Classic LB is ignored from creation wait logic.
=> Classic LB is ignored from creation wait logic.

duplocloud/resource_duplo_infrastructure.go
DUPLO-4820 : Error: No infrastructure named 'default' was found
=> DUPLO-4820 : Error: No infrastructure named 'default' was found

duplocloud/resource_duplo_infrastructure.go
Error: No infrastructure named 'default' was found.
=> Error: No infrastructure named 'default' was found.

docs/data-sources/k8_secret.md, docs/resources/k8_secret.md, duplocloud/resource_duplo_aws_cloudfront_distribution.go, duplocloud/resource_duplo_k8_secret.go, duplosdk/aws_cloudfront_distribution.go, duplosdk/tenant_aws_cloud_resources.go
- Support of cloudfront attribute `function_association`.
- Fix : cannot unmarshal response from JSON: json: cannot unmarshal object into Go struct field DuploAwsCloudfrontLambdaFunctionAssociation.DefaultCacheBehavior.LambdaFunctionAssociations.Items.EventType of type string
=> DUPLO-5427: Support of cloudfront attribute `function_association`.

duplocloud/resource_duplo_infrastructure.go, duplosdk/infrastructure.go
- Data source `duplocloud_infrastructure` does not return subnets if the name has a hyphen.
=> Data source `duplocloud_infrastructure` does not return subnets if the name has a hyphen.

docs/resources/rds_instance.md, duplocloud/resource_duplo_rds_instance.go, duplosdk/rds_instance.go
- `allocated_storage` attribute added for duplocloud_rds_instance.
=> `allocated_storage` attribute added for duplocloud_rds_instance.

duplocloud/resource_duplo_lbconfigs.go, duplosdk/replication_controller.go
- target_group_arn field is added on duplocloud_duplo_service_lbconfigs.
=> target_group_arn field is added on duplocloud_duplo_service_lbconfigs.

duplocloud/resource_duplo_aws_lambda_function.go
python 3.1 support for lambda runtime. (blocpower-duplo)
=> DUPLO-10062: python 3.1 support for lambda runtime

duplocloud/resource_duplo_infrastructure.go, duplocloud/resource_duplo_infrastructure_setting.go, duplocloud/utils_test.go, duplosdk/infrastructure.go
Deprecate `custom_data` for infrastructure settings.
> Fix [#1](https://app.clickup.com/t/8655600/DUPLO-9414)
=> DUPLO-9414 deprecate custom_data from infra settings

duplosdk/aws_cloudwatch.go
- Avoid passing empty string for ScheduleExpression.
=> Avoid passing empty string for ScheduleExpression.

docs/resources/aws_lambda_function.md, duplocloud/resource_duplo_aws_lambda_function.go
make `ephemeral_storage` Default to 512 if not provided
=>  DUPLO-11537: Set default to 512, remove Computed

duplocloud/data_source_duplo_tenant_config.go
Fix terraform state showing null fields.
1. Run `terraform apply` on the following data source
```
data "duplocloud_tenant_config" "config" {
tenant_id     = "64813f67-7df1-438d-95ea-c3cc2b151717"
}
```
2. Run `terraform state show data.duplocloud_tenant_config.config`
```
data "duplocloud_tenant_config" "config" {
id        = "64813f67-7df1-438d-95ea-c3cc2b151717"
metadata  = [
{
key   = "delete_protection"
value = "true"
},
{
key   = "kms_key_rotation_enabled"
value = "true"
},
{
key   = "enable_node_to_node_encryption_for_es"
value = "true"
},
{
key   = "enforce_ssl_for_es"
value = "true"
},
{
key   = "use_latest_tls_cipher_for_es"
value = "true"
},
{
key   = "enable_ecs_cloud_watch_logging"
value = "true"
},
{
key   = "enable_alerting"
value = "true"
},
]
tenant_id = …
```
=> set id for state

duplocloud/resource_duplo_rds_instance.go
```
~ resource "duplocloud_rds_instance" "theirdb" {
id                  = "v2/subscriptions/09da93de-cfc0-42bc-9cc5-5f11de485cd2/RDSDBInstance/retestbug1"
name                = "retestbug1"
- storage_type        = "aurora" -> null
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
```
╰─ terraform apply              
random_password.mypassword: Refreshing state... [id=none]
duplocloud_rds_instance.theirdb: Refreshing state... [id=v2/subscriptions/09da93de-cfc0-42bc-9cc5-5f11de485cd2/RDSDBInstance/retestbug1]
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```
=> make `storage_type` Computed = true

.gitignore, .vscode/launch.json, README.md, main.go
We currently debug this provider using a log strategy which I think presents several drawbacks like the following:
1. Relevant logs in the output file are usually mixed with a lot of noise logs we are not really interested in
2. Rerunning the provider after changes requires running a bunch of commands to removing tf lock files, existing plugins and make a new local installation of the provider.
The debugger setup allow us to define breakpoints and get laser focused information in regards to what we want to inspect. Debugger development helps avoid having to remove and re-install the provider locally after every code change.
=> DUPLO feat: allow provider development with debuggers

duplocloud/resource_duplo_aws_host.go
Adds support for the `allocated_public_ip` attribute on the `duplocloud_aws_host`. Previously, this attribute was only a passthrough value for the resource to the Duplo API. However, the Duplo API does not rely on this flag when determining the configuration of the network interface controller.
1. If the `allocated_public_ip` property is set to true (default is false) and there is no `NetworkInterface` config provided in the `NetworkInterfaces` attribute, then a `NetworkInterface` config is created for it with the `subnet_id` attribute set to be the tenant's external subnet assigned to the provided `zone` (default zone is 0).
2. For all existing `NetworkInterface` configs, if the `network_interface_id` was left blank, the `subnet_id` attribute is set to be the tenant's subnet assigned to …
=> DUPLO-13203 support for duplocloud_aws_host.allocated_public_ip

duplocloud/data_source_duplo_plan_settings.go
* data source duplocloud_plan_settings: dns_setting: MaxItems is for configurable attributes,there's nothing to configure on computed-only field
> Fix [#1]()
=> DUPLO-13535 fix: remove MaxItems which errors out for computed fields

CHANGELOG.md, Makefile, duplocloud/provider_test.go, duplocloud/resource_duplo_aws_host.go, duplocloud/resource_duplo_aws_host_test.go, internal/duplocloudtest/helpers.go, internal/duplosdktest/emulator.go, internal/duplosdktest/fixtures.go, internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/aws_host/i-a4a64e4407f5ae678.json, internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/external_subnets/1.json, internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/external_subnets/2.json, internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/internal_subnets/1.json, internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/internal_subnets/2.json
DUPLO-15007: Happy path tests for duplocloud_aws_host
- Adds happy path tests for `duplocloud_aws_host`
- Fixes missing network interfaces for `duplocloud_aws_host`
- Export fixtures methods.
- Fix fixture delete bug where the cached fixture list was not invalidated.
- Fix fixture lists not being sorted
- ...
=> DUPLO-15007: Happy path tests for duplocloud_aws_host

CHANGELOG.md, duplocloud/resource_duplo_aws_elasticsearch.go
[DUPLO-14500] - TF: Not able create OpenSearch with (warm enable =false and cold storage=false)
- later commits overriden my changes
- ...
- ...
___
bug_fix
___
- Corrected the logic for setting `ColdStorageOptions` in AWS Elasticsearch configurations to address issues when cold storage is disabled.
- This fix ensures that Elasticsearch domains are correctly configured without cold storage when specified by the user.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>resource_duplo_aws_elasticsearch.go</strong><dd><code>Fix Cold Storage Options Handling in AWS Elasticsearch</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> [DUPLO-14500] - TF: Not able create OpenSearch with (warm enable =false and cold storage=false)

CHANGELOG.md, duplocloud/resource_duplo_aws_lambda_function.go, duplosdk/aws_lambda_function.go
Added dead letter queue configuration to AWS lambda
Added dead letter queue configuration to AWS lambda
___
enhancement
___
- Added support for configuring a dead letter queue (DLQ) for AWS Lambda functions, allowing specification of an SNS topic or SQS queue for failed invocation notifications.
- Implemented CRUD operations and Terraform state management for the new `dead_letter_config` feature in AWS Lambda resource.
- Updated SDK with `DuploDeadLetterConfig` struct to support dead letter configuration in Lambda functions.
- Updated CHANGELOG.md to document the addition of dead letter queue configuration support.
___
<tr> …
=> DUPLO-11165: Added dead letter queue configuration to AWS lambda

CHANGELOG.md, duplocloud/resource_duplo_aws_elasticsearch.go, duplosdk/aws_elasticsearch.go
Creation of Elastic search cluster was crashing when `dedicated_master_type` field of cluster config was not defined because it was implicitly being assigned `{ Value: null }` by Go. The unexpected structure made AWS throw a non descriptive error message `Value cannot be null, parameter : key`. This PR makes this field into a pointer so we may properly assign it `null` when it is not defined. AWS lets us create it properly with no errors if dedicated_master_type is null.
This PR also fixes attribute mapping between API response and TF state. The correct version field is called `EngineVerion` instead of `ElasticSearchVersion`.
- Makes `dedicated_master_type` into a pointer so it is null if absent from parameters when creating `DuploElasticSearchDomainRequest`
- …
=> DUPLO-13077 fixes broken elastic search creation with no dedicated master type and fixes elasticsearch_version mapping

CHANGELOG.md, duplocloud/resource_duplo_plan_settings.go
Plan setting resource Bug
Terraform fails to set unrestricted_ext_lb fixed
- Looking for change on unrestricted_ext_lb
- Updating unrestricted_ext_lb attribute
- ...
=> DUPLO 14317 Plan Setting Bug 

CHANGELOG.md, docs/resources/aws_dynamodb_table_v2.md, docs/resources/ecache_instance.md, duplocloud/resource_duplo_ecache_instance.go, duplosdk/ecache_instance.go, examples/resources/duplocloud_ecache_instance/resource.tf
Added support attribute for setting cluster mode and number of shards
Added support attribute NumberOfShards and EnableClusterMode
- Added schema attribute enable_cluster_mode and number_of_shards
- Added request/response attribute EnableClusterMode and NumberOfShards
- Updated documents
- ...
=> Duplo 15257 Elastic cache support

CHANGELOG.md, duplocloud/resource_duplo_ecache_instance.go
Change occuring for unchange on plan
Fix for on planing of already created memcache resource without change, showing changes 
- Removed default value on number of shards, replaced force new with computed
- No of shards validation handled inside code
- ...
=> DUPLO-15831 MEMCACHE no change bug

CHANGELOG.md, duplocloud/resource_duplo_aws_lambda_function.go
Extended python version support for lambda function
- Added version 3.11 and 3.12 python version in schema validation under runtime
- Implemented conditional check on gov region under lambda environment for runtime python3.12
- ...
=> DUPLO 15611 Add python version  3.11 and 3.12 support for lambda runtime

CHANGELOG.md, duplocloud/resource_duplo_infrastructure.go, duplosdk/infrastructure.go
Fix for dereference
Handled dereference issue for infrastructure resource
- Extended polling time
- Handled nil pointer exception
- ...
=> Duplo 15350 Infrastructure dereference bug fix 

CHANGELOG.md, duplocloud/resource_duplo_aws_lambda_function.go, duplosdk/aws_lambda_function.go
added architecture field to lambda function
- ...
- ...
- ...
___
enhancement
___
- Added the ability to specify the instruction set architecture for AWS Lambda functions, supporting both `[x86_64]` and `[arm64]`.
- Updated the Terraform provider and SDK to handle the new `architectures` field during Lambda function creation and updates.
- Ensured compatibility with existing configurations by making the `architectures` field optional.
___
<tr>
<td>
<details>
<summary><strong>resource_duplo_aws_lambda_function.go</strong><dd><code>Add Architecture Support for AWS Lambda Functions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> DUPLO-14315: added architecture field to lambda function

CHANGELOG.md, duplocloud/resource_duplo_user.go
Plugin crash when user exist 
Olugin crashes while throwing user exist error in `duplocloud_user` resource
- Handle nil pointer exception
- ...
- ...
=> Duplo 16118 Plugin Crash

CHANGELOG.md, duplocloud/data_source_duplo_gcp_node_pool.go, duplocloud/data_source_duplo_gcp_node_pools.go
Schema fix
Schema fix for datasource for node pool
- Schema fix for `duplocloud_gcp_node_pool` data source
- ...
- ...
=> Duplo 16115 schema fix

CHANGELOG.md, docs/resources/azure_virtual_machine.md, duplocloud/resource_duplo_azure_virtual_machine.go
DUPLO-16672  fixed.
- ...
- ...
- ...
___
enhancement, bug_fix
___
- Introduced support for custom prefixes in Azure VM names to allow for more flexible naming conventions.
- Added a new `fullname` attribute to Azure VM resources to store the full name of the VM, enhancing traceability and management.
- Updated the Azure VM resource documentation to include the new `fullname` attribute.
- Fixed logging and resource management to correctly handle the `fullname` of Azure VMs across create, read, update, and delete operations.
___
<tr>
<td>
<details>
<summary><strong>resource_duplo_azure_virtual_machine.go</strong><dd><code>Suppor …
=> DUPLO-16672: Azure TF> duplocloud_azure_virtual_machine resource apply fails with an error when prefixes are enabled

CHANGELOG.md, duplocloud/data_source_duplo_gke_credentials.go, duplocloud/resource_duplo_lbconfigs.go, duplosdk/replication_controller.go
GKE datasource exception handling for kubernetes enable for plan
- Checking kubernetes enable for gke plan
- ...
- ...
___
bug_fix, enhancement
___
- Improved error handling in `duplocloud/data_source_duplo_gke_credentials.go` to provide clearer error messages when Kubernetes JIT access is not enabled for a plan.
- Minor code formatting adjustment in `duplocloud/resource_duplo_lbconfigs.go`.
- Updated the CHANGELOG to include the recent fixes in GKE and EKS datasource error handling.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>data_source_duplo_gke_credentials.go</strong><dd><code>Improved …
=> Duplo 15896 kube error msg for GKE datasource

CHANGELOG.md, duplocloud/resource_duplo_ecs_service.go
This PR has fix for error related to `duplocloud_ecs_task_definition` resource update.
Now on update of task_definition
exisiting service related to task_definition is getting destroyed
task_definition getting destroyed
task_definition got created
service related to task_definition got created
- Made arn field force new. Which helps in updating task-definition along with associated service
- ...
- ...
___
bug_fix, enhancement
___
- Marked the `task_definition` field in `duplocloud_ecs_service.go` with `ForceNew` to ensure that the ECS service is recreated when the task definition is updated.
- Updated the CHANGELOG to document the fix applied to the ECS service update process.
___
<table><thead><tr><th></th><th …
=> DUPLO 16595 Bug fix on update of taskdefnition

CHANGELOG.md, docs/resources/gcp_sql_database_instance.md, duplocloud/resource_duplo_gcp_sql_database.go, duplosdk/gcp_sql_database.go
Add support for root password
added support for password for gcp sql resource
- Added support for root password passing
- ...
- ...
___
___
- Added support for specifying a root password for GCP SQL database instances, enhancing security and customization.
- Implemented logic to require a root password for certain SQL Server versions, improving compliance with best practices.
- Updated SDK to support root password management for GCP SQL databases.
- Updated documentation and changelog to reflect the new feature and its usage.
___
<tr>
<td>
<details> …
=> DUPLO-14760 Mandatory field "Root Password" for database creation is missing for Cloud SQL databases.

CHANGELOG.md, docs/data-sources/asg_profiles.md, docs/resources/asg_profile.md, duplocloud/resource_duplo_asg_profile.go, duplosdk/asg.go
Removed schema attribute use_launch_template
Removed schema attribute use_launch_template from duplocloud_asg_profile resource
- Removed schema attribute use_launch_template from duplocloud_asg_profile resource
- ...
- ...
___
___
- Removed the `use_launch_template` attribute from the autoscaling group schema and related documentation.
- Updated `DuploAsgProfile` struct to exclude the `UseLaunchTemplate` field.
- Updated documentation in both data sources and resources to reflect the removal of `use_launch_template`.
- Added changelog entry for the removal of `use_launch_template` handling and documentation.
___ …
=> DUPLO 11726 removed use_launch_template attribute form duplocloud_asg_profile

duplocloud/data_source_duplo_gcp_node_pool.go, duplocloud/data_source_duplo_gcp_node_pools.go, duplocloud/resource_duplo_gcp_k8_node_pool.go
This PR contains support for adding ResourceLabels for `duplocloud_gcp_node_pool` resource
- Support added for resource creation and updation of resource_labels
- Support added for data source
- ...
=> DUPLO 17038  Support for ResourceLabels for duplocloud_gcp_node_pool tf resource

docs/data-sources/gcp_node_pool.md, docs/resources/aws_elasticsearch.md, docs/resources/gcp_node_pool.md, docs/resources/plan_settings.md, docs/resources/rds_instance.md, duplocloud/resource_duplo_rds_instance.go, duplosdk/rds_instance.go
Added support to `enable_iam_auth` attribute in `duplocloud_rds_instance`
- Sets enable_iam_auth on create for duplocloud_rds_instance
- ...
=> DUPLO 17015 Add support for enable_iam_auth in rds_instance

duplocloud/resource_duplo_lbconfigs.go
Bug fix for tfstate not getting update for `allow_global_access` schema attribute for `duplocloud_duplo_service_lbconfigs` resource
- PR sets value for `allow_global_access` during read
- ...
=> DUPLO 17067 TFstate update fix 

CHANGELOG.md, docs/data-sources/gcp_node_pools.md, duplocloud/data_source_duplo_gcp_node_pools.go, duplocloud/resource_duplo_gcp_k8_node_pool.go, examples/data-sources/duplocloud_gcp_node_pools/data-source.tf, examples/data-sources/duplocloud_gcp_sqls/data-source.tf
Fixed listing of Nodepools 
- updated document
- Fixed State not getting set for data source of node pools datasource
- [ ✓] Manually, on my local system
- ...
___
bug_fix, enhancement, documentation
___
- Enhanced logging and corrected data handling in GCP Node Pools data source.
- Fixed `cgroup_mode` field type and state setting in GCP Node Pools and K8 Node Pool resource.
- Updated documentation and examples for GCP Node Pools and SQL Database Instances.
- Documented recent fixes and enhancements in the CHANGELOG.
___
<tr>
<td>
<details> …
=> Duplo 16117 Nodepool List Datasource Fix

.github/workflows/dev-check.yml, .github/workflows/dev-test.yml, .github/workflows/finish-release.yml, .github/workflows/release-publish.yml, .github/workflows/start-release.yml
Updated GitHub actions that used node@16.
- `actions/checkout@v3` -> @v4
- `agolangci/golangci-lint-action@v3` -> @v5
- `actions/setup-go@v4`  -> @v5
=> DUPLO-9842 Update to Github Actions

docs/resources/asg_profile.md, docs/resources/aws_host.md, duplocloud/resource_duplo_aws_host.go
Updated default value and docs for  `prefered_user_data` for  resource  `duplocloud_asg_profile` and `duplocloud_aws_host`
- ...
- ...
- [ ✓] Manually, on my local system
- ...
___
___
- Changed the default value of `prepend_user_data` in `duplocloud/resource_duplo_aws_host.go` to `true`.
- Updated the documentation in `docs/resources/asg_profile.md` and `docs/resources/aws_host.md` to reflect the new default value of `prepend_user_data`.
___
<tr>
<td>
<details>
<summary><strong>resource_duplo_aws_host.go</strong><dd><code>Update default value of `prepend_user_data` in AWS host …
=> DUPLO-14998 Updated default value and docs 

duplocloud/resource_duplo_s3_bucket.go, duplosdk/admin.go, duplosdk/tenant_aws_cloud_resources.go
S3 prefix support added in terraform.
S3 prefix support added in terraform.
- ...
=> DUPLO-17377: S3 prefix support added in terraform.

docs/resources/aws_dynamodb_table_v2.md, duplocloud/resource_duplo_aws_dynamodb_table_v2.go, duplosdk/utils.go
Fixed creation issue for `duplocloud_aws_dynamodb_table_v2` resource due to fixes related to dynamo table name
- Added `fullname` computed attribute to hold table name with duplo prefix
- Fixed create and update context, setting resource Id as tenant-id/fullname
- ...
=> DUPLO-17370 Unable to create duplocloud_aws_dynamodb_table_v2 resource.

duplocloud/resource_duplo_aws_efs_file_system.go, duplosdk/aws_efs.go, duplosdk/aws_efs_lifecycle_policy.go
Fix for `mount_targets` details are missing in TF state file for `duplocloud_aws_efs_file_system` resource
- Added API that returns details for `mount_targets` schema attribute for resource `duplocloud_aws_efs_file_system`
- ...
- ...
___
enhancement
___
- Added support for retrieving and displaying mount target details in the `duplocloud_aws_efs_file_system` resource.
- Introduced new data structures in the SDK to handle mount target and lifecycle state information.
- Enhanced the EFS resource read function to fetch and set mount target details from the API.
___
<tr>
<td>
<details> …
=> DUPLO-17034 Mount targets details are missing in TF state file

duplocloud/resource_duplo_gcp_scheduler_job.go
Fixed `duplocloud_gcp_scheduler_job` plugin crash for app_engine_target 
- Replaced initialisation of attribute from HTTPTarget to AppEngineTarget
- ...
- ...
=> DUPLO 17175 GCP:duplocloud_gcp_scheduler_job with app_engine_target - plugin crash

duplocloud/diff_utils.go, duplocloud/resource_duplo_ecs_task_definition.go
fix for `family` attribute of `duplocloud_ecs_task_definition` resource shows resource replacement on no change
- Introduced new attribute `full_family_name` as computed attribute which will hold family name with duplo prefix which will avoid replacement if no change in family attribute due to duplo prefix
- ...
=> DUPLO 17150 duplocloud_ecs_task_definition: Terraform shows difference in plan with no changes if Family name is provided without duplo prefix

duplocloud/resource_duplo_aws_dynamodb_table_v2.go
Fixed : Unable to create `duplocloud_aws_dynamodb_table_v2` resource when `is_point_in_time_recovery` is set to ‘true’.
- Updating is_point_in_time_recovery status using dynamo full name
- ...
- ...
=> DUPLO 17447  Unable to create 'duplocloud_aws_dynamodb_table_v2' resource when ‘is_point_in_time_recovery’ is set to ‘true’.

duplocloud/resource_duplo_aws_dynamodb_table_v2.go, duplosdk/utils.go
- Implements a before hook function for each CRUD operation on DynamoDB tables.
- Prefixes the table name with "duploservices" and the tenet name as expected by the API.
-
=> DUPLO-16758/duplo-prefix

duplocloud/resource_duplo_aws_dynamodb_table_v2.go
Fixed Regression issue for `duplocloud_aws_dynamodb_table_v2` resource
- Removed beforehook function usage due to conficting resource name
- Added logic to handle feb release resource creation
- ...
=> Duplo 17486 Not able to create DynamoDBV2. getting error "Root object was present, but now absent"

duplocloud/data_source_duplo_eks_credentials.go
Fixed for azure platform to show "No Kubernetes cluster for this plan" error  for data "duplocloud_eks_credentials"
- Added check for AKSconfig exist
- ...
- ...
=> DUPLO-15896 "No Kubernetes cluster for this plan" error should be displayed when the provided plan does not have AKS

duplocloud/resource_duplo_gcp_firestore.go
This PR contains fix for DUPLO-DUPLO-17361 `enable_point_in_time_recovery` not getting set for `duplocloud_gcp_firestore` resource
and 
fix for DUPLO-17362  `duplocloud_gcp_firestore` resources update if `type` is changed from "FIRESTORE_NATIVE" to "DATASTORE_MODE" which should not be allowed "DATASTORE_MODE" to "FIRESTORE_NATIVE" is allowed
- enable_point_in_time_recovery status typo fix
- Added diffsuppress function to suppress change if old=FIRESTORE_NATIVE and new =DATASTORE_MODE
- ...
=> DUPLO-17362 DUPLO-DUPLO-17361  BUG FIX

duplocloud/resource_duplo_infrastructure.go, duplosdk/infrastructure.go
Updated `duplocloud_infrastructure` resource added `cluster_ip_cidr` schema attribute
- Added schema attribute `cluster_ip_cidr`
- Made applicable for gcp and standard gke
- ...
=> Duplo 17581 Support for cluster ip cidr for gcp

duplocloud/resource_duplo_service_params.go, duplosdk/agnostic_load_balancer.go, duplosdk/client.go, duplosdk/replication_controller.go
This PR adds timeout errors to the retryable error check for retries in service param calls. It also increases timeout tolerance to allow request to succeed more easily.
This PR adds retries with exponential backoff and jitter to GetWafInLb API call. It also fixes the error thrown when the call fails so we dont fail silently.
- Increases timeout limit for duplo client
- Adds timeout error check as retryable
- Fixes error thrown when GetWafInLb fails
- Adds retries with jitter and exponential backoff to GetWafInLb API call
QA testing recommended to sanity checking
___
Bug fix, Enhancement
___
- Fixed error handling in `resourceDuploServiceParamsCreateOrUpdate` to return `clientError` instead of `err`.
- Enhanced retry logic for `TenantUpdateLbSettings` and …
=> [DUPLO-17469, DUPLO-17888] fix: adjust duplo client timeout and include timeout error in retriable error check for TenantUpdateLbSettings

duplocloud/provider.go
Added support to fetch provider env variable detail in upper case
- added check for duplo_token and duplo_host in uppercase to fetch the value
- ...
- ...
=> DUPLO 17945 Support Duplo provider env variable with uppercase

duplocloud/resource_duplo_k8s_cron_job.go
Fixed setting of missing tenant_id on read context for `duplocloud_k8s_cron_job` resource
- set tenant_id on read context
- ...
- ...
=> DUPLO-17972 No tenant id in imported k8s_cron_job resources 

docs/data-sources/asg_profiles.md, docs/data-sources/native_hosts.md, docs/resources/asg_profile.md, docs/resources/aws_host.md, duplocloud/resource_duplo_aws_host.go, duplosdk/native_hosts.go
Added public_ip_address for `duplocloud_aws_host` resource and updated docs
- Updated read context to read public ip 
- Updated schema added puplic_ip_address
- ...
=> DUPLO 18002 Hosts don't output public ip

duplocloud/resource_duplo_aws_elasticsearch.go, duplosdk/aws_elasticsearch.go
Allowing creation of opensearch without storage_size for instance type i3. and im4gn. for duplocloud_aws_elasticsearch resource
- Removed default value of storage_size , passing null EBSOption object if storage_size not specified.
- Removed EBSOption assignment in update since storage_size is force new
- ...
=> DUPLO-18013 TF: Support Opensearch instances with no EBS storage

duplocloud/data_source_duplo_k8_secrets.go
Fixed masking bug for secret readonly for non readonly user for  duplocloud_k8_secrets data source
- removed line that sets user_readonly flag which overrights actual state
- fixed secret_annotations set issue
- ...
=> DUPLO-18931 Data source duplocloud_k8_secrets mask non read only user secrets

duplocloud/data_source_duplo_k8_secret.go, duplocloud/data_source_duplo_k8_secrets.go
- ...
- ...
- ...
___
Bug fix
___
- Corrected the system setting key from `AllowReadonlySecrets` to `AllowReadonlyK8sSecrets` in `data_source_duplo_k8_secret.go`.
- Added a nil check for `access` before comparing its value in both `data_source_duplo_k8_secret.go` and `data_source_duplo_k8_secrets.go`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>data_source_duplo_k8_secret.go</strong><dd><code>Fix system setting key and add nil check in K8 secret read</code></dd></summary>
<hr>
duplocloud/data_source_duplo_k8_secret.go
<li>Corrected system setting key from …
=> DUPLO-16746 plugin crash issue fix

CHANGELOG.md, duplocloud/resource_duplo_asg_profile.go, duplosdk/asg.go
Adds support to enabling/disabling metrics for ASGs
- Introduces new schema property `enabled_metrics` on ASG profile resource
Must merge after merging https://github.com/duplocloud-internal/duplo/pull/2819
___
Enhancement
___
- Introduced a new schema property `enabled_metrics` on the ASG profile resource to support enabling/disabling metrics.
- Updated the `DuploAsgProfile` struct to include the `EnabledMetrics` field.
- Modified functions to handle the new `enabled_metrics` property, including `asgProfileToState`, `expandAsgProfile`, and `needsResourceAwsASGUpdate`.
___
<tr>
<td>
<details> …
=> DUPLO-18177 feat: add support for enabling/disabling metrics in ASG resources

CHANGELOG.md, docs/resources/aws_ecr_repository.md, duplocloud/resource_duplo_aws_ecr_repository.go, duplosdk/aws_ecr_repository.go, examples/resources/duplocloud_aws_ecr_repository/resource.tf
Re-applies PR https://github.com/duplocloud/terraform-provider-duplocloud/pull/591 reverted due to unmerged backend changes
- re-applies force delete support for ECR repositories
Merge after merging https://github.com/duplocloud-internal/duplo/pull/2910
___
Enhancement, Documentation
___
- Added `force_delete` attribute to the ECR repository schema to allow forced deletion.
- Updated `AwsEcrRepositoryDelete` function to handle `forceDelete` parameter and modify API endpoint accordingly.
- Documented the new `force_delete` option in the CHANGELOG and resource documentation.
- Updated example resource configuration to include `force_delete` attribute.
___ …
=> DUPLO-19011 feat: allow option to force delete ECR repositories from duplo provider

duplocloud/resource_duplo_aws_dynamodb_table_v2.go, duplocloud/utils.go, duplosdk/aws_dynamo_db.go
Kept support for below available service.
Fixed name issue, currently table will be created with prefix since some update api expects duplo prefix
Available api for july 2024 release
```
[HttpGet] "dynamodbTableV2/{id}"
[HttpPost]"dynamodbTableV2"
[HttpDelete]"dynamodbTableV2/{id}"
[HttpPut] dynamodbTableV2/{id}/ttl"
[HttpPut] "dynamodbTableV2/{id}/point-in-time-recovery"
```   
- ...
- ...
- [_/ ] Manually, on a remote test system
- ...
=> Duplo 19647 , Duplo 19648 jul tag and name issue dynamodb

CHANGELOG.md, duplosdk/aws_ecr_repository.go
We have changed the data contract for force_delete operations and this needs to reflect in the client code of Duplo's Terraform provider
- Adjust data contract for force_delete ecr operations
No
___
Bug fix
___
- Adjusted the URL path construction for force delete ECR operations in `AwsEcrRepositoryDelete` function.
- Changed the order of URL path segments to correctly reflect the new data contract.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>aws_ecr_repository.go</strong><dd><code>Fix URL path construction for force delete ECR operations</code></dd></summary>
<hr>
duplosdk/aws_ecr_repository.go
<li>Adjusted the URL path construction …
=> DUPLO-18177 fix: add missing adjustment to change in data contract

duplocloud/data_source_duplo_eks_credentials.go
Checking if plan has k8s enabled if plan is non default and has infra response. Otherwise fetching k8s config
- updated code for duplocloud_eks_credentials data-source
- ...
- [ ☑️] Manually, on a remote test system
- ...
=> DUPLO-19736 Data resource duplocloud_eks_credentials handle case where infra does not exists

docs/resources/azure_virtual_machine.md, duplocloud/diff_utils.go, duplocloud/resource_duplo_azure_virtual_machine.go, duplocloud/utils.go, duplosdk/native_hosts.go
Added support for disk_control_type to duplocloud_azure_virtual_machine resource, added duplo_associated_nic_name to duplo manged tag list
- Updated resource schema and duplo manged tag list
- Updated docs
- ...
=> Duplo 19094 Support to set VM `Disk Controller Type` to `NVMe` via TF

docs/resources/azure_virtual_machine.md, duplocloud/resource_duplo_azure_virtual_machine.go, duplosdk/native_hosts.go
Support added  for encryption at host and security type and other related schema attribute for duplocloud_azure_virtual_machine resource
- Added support for encryption_at_host, security_type, enable_vtpm, enable_security_boot 
- Updated doc
- ...
=> DUPLO-19094 Support for below specification during VM creation via TF

docs/resources/azure_k8s_cluster.md, duplocloud/resource_duplo_azure_k8s_cluster.go
Made name and resource_group_name optional for backward compatibility, if name not passed infra name will be assigned
- schema behaviour change
- updated doc
- ...
=> Duplo 19031 Azure> TF> Feature to add customized name for AKS and resource group via TF

docs/resources/infrastructure_setting.md, duplocloud/resource_duplo_infrastructure_setting.go
potential fix
- ...
- ...
- ...
___
Documentation, Enhancement
___
- Enhanced the `setting` field documentation in both the Go source file and the Markdown documentation by adding a detailed table of key/value pairs.
- Clarified the note regarding the format of the `EksControlplaneLogs` value.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>resource_duplo_infrastructure_setting.go</strong><dd><code>Enhance `setting` field documentation with detailed table</code></dd></summary>
<hr>
duplocloud/resource_duplo_infrastructure_setting.go
<li>Added detailed description for <code>setting</code> field with a table of key/value …
=> DUPLO-20452 Infra Setting document fix

duplocloud/resource_duplo_aws_dynamodb_table_v2.go, examples/resources/duplocloud_aws_dynamodb_table_v2/import.sh
Fixed Get API fail on import of duplocloud_aws_dynamodb_table_v2 resource
- Initializing name to fullname if fullname is empty
- ...
- ...
=> DUPLO-20874 TF Import: Dynamo DB missing name in Get API

duplocloud/resource_duplo_aws_dynamodb_table_v2.go
Fix related to Feb release creates dynamo db without duplo prefix while july relase creates dynamo db with prefix and need full name to fetch table details
- fallback get api attempt with short name if fullname fails
- ...
- ...
=> DUPLO-20879 Fallback implemented

CHANGELOG.md, duplocloud/resource_duplo_aws_dynamodb_table_v2.go
Reverts duplocloud/terraform-provider-duplocloud#640
___
Bug fix
___
- Removed the fallback mechanism for handling errors during DynamoDB table retrieval and deletion, simplifying the code.
- Enhanced error handling by directly addressing errors without attempting a fallback.
- Cleaned up redundant code related to fallback attempts, improving code maintainability.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>resource_duplo_aws_dynamodb_table_v2.go</strong><dd><code>Remove fallback mechanism and simplify error handling</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
duplocloud/resource_duplo_aws_dynamodb_table_v2.go
<li>Removed fallback mechanism for …
=> Revert "DUPLO-20879 Fallback implemented"

duplocloud/data_source_duplo_aws_ssm_parameter.go, duplocloud/data_source_duplo_aws_ssm_parameters.go, duplocloud/resource_duplo_aws_ssm_parameter.go, duplosdk/client.go
Masking ssm parameter secure string value in log
- skipping log at doApi function for get and list api for ssm param
- masking value of list and get api if type is SecureString
- ...
=> DUPLO-21079 Mask SSM parameter of type secret string in terraform logs.

CHANGELOG.md, docs/resources/ecache_instance.md, duplocloud/resource_duplo_ecache_instance.go
DUPLO-21081 DUPLO-21083:  add docs to log delivery config, validate duplicate log types, validate lower verision allowed for log type## Summary of changes
- add docs to log delivery config
- validate duplicate log types
- validate lower verision allowed for log type
- ...
___
___
- Enhanced log delivery configuration by adding validation to prevent duplicate log types.
- Implemented version checks for log types to ensure compatibility with specified engine versions.
- Updated documentation to reflect changes in log delivery configuration requirements and examples.
- Updated CHANGELOG to document the enhancements and validations added.
___ …
=> DUPLO-21081 DUPLO-21083:  add docs to log delivery config, validate duplicate log types, validate lower verision allowed for log type

CHANGELOG.md, docs/resources/azure_k8_node_pool.md, duplocloud/resource_duplo_azure_k8_node_pool.go
Set default value as Delete for eviciton_policy in duplocloud_azure_k8_node_pool resource
Set default value as Delete for eviciton_policy in duplocloud_azure_k8_node_pool resource when priority is set as spot and no value for eviction_policy is set.
- Implement Custom diff to check if eviction_policy is empty to set Delete as default value for Spot priority type for scale_priority
- ...
- [ ✓] Manually, on my local system
- ...
___
___
- Added a custom diff validator to ensure proper handling of `scale_priority` attributes, preventing unsupported configurations.
- Set the default value for `eviction_policy` to "Delete" when `priority` is set to "Spot" in the `duplocloud_azure_k8_node_pool` resource.
- Updated documentation to reflect …
=> Duplo-21053 TF:Azure:AgentPool: Make 'Delete' as a default Scale Set Eviction Policy for "Scale Set Priority" = "Spot"

CHANGELOG.md, duplocloud/resource_duplo_azure_k8_node_pool.go
Regression Fix 
Added missing length check on a slice in customdiff func
- added.length check for a slice of scalePriority object in customdiff func of duplocloud_azure_k8_node_pool resource
- ...
- ...
___
Bug fix, Documentation
___
- Fixed a regression issue in `duplocloud_azure_k8_node_pool` by adding a length check for the `scale_priority` slice to prevent crashes when the scale set priority is not specified.
- Updated the changelog to document the regression fix.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>resource_duplo_azure_k8_node_pool.go</strong><dd><code>Add length check for …
=> DUPLO-21141 TF:duplocloud_azure_k8_node_pool: Provider plugin crashed when the scale set priority is not specified in Terraform

CHANGELOG.md, docs/resources/rds_instance.md, duplocloud/resource_duplo_rds_instance.go, examples/resources/duplocloud_rds_instance/resource.tf
Rename attribute and delay fix
Renamed attribute enable to enabled.
Fixed Delay issue for performance insights
- Renamed attribute enable to enabled
- Moved performance insights body as part of post request in create context
- ...
___
___
- Renamed the `enable` attribute to `enabled` for performance insights in the RDS instance schema.
- Updated the logic to handle the performance insights configuration, including the removal of redundant update code.
- Updated the documentation to reflect the renaming of the attribute.
- Modified example resource configuration to use the new `enabled` attribute.
___ …
=> DUPLO-21153 TF:RDS: performance insight: change flag from enable to enabled

CHANGELOG.md, duplocloud/resource_duplo_rds_instance.go, examples/resources/duplocloud_rds_instance/resource.tf
Implemented rds parameter validation and allowed cluster db creation and update for performance insights
Implemented validation on rds instance that support performance insight and checking storage_type for aurora dbs for duplocloud_rds_instance resource
- Added customdiff function for rds parameter validation
- Added example of cluster db for performance insights
- ...
___
Enhancement, Documentation
___
- Implemented a new `CustomizeDiff` function to validate RDS parameters, ensuring compatibility of engine and instance size combinations.
- Streamlined the process of enabling and disabling performance insights for RDS instances.
- Added validation for Aurora database storage types to ensure …
=> Duplo-21171 RDS TF: Performance insight enable is not working for Cluster DB writer instance. it works when enabled through the API.

CHANGELOG.md, docs/resources/ecache_instance.md, duplocloud/resource_duplo_ecache_instance.go, templates/resources/ecache_instance.md.tmpl
DUPLO-21150: TF Doc: Update doc to include samples for Redis logging configuration
- add sample to templates
- ...
- None
___
Documentation, Enhancement
___
- Added new documentation examples for creating an Amazon ElastiCache of type Redis with log delivery configuration and automatic failover enabled.
- Updated the Go schema description for `destination_type` by removing the reference link.
- Enhanced the documentation by providing detailed examples for log delivery configuration in both Markdown and template files.
___
<tr>
<td>
<details>
<summary><strong>resource_duplo_ecache_instance.go</strong><dd><code>Update schema …
=> DUPLO-21150: TF Doc: Update doc to include samples for Redis logging configuration

CHANGELOG.md, duplocloud/resource_duplo_azure_k8_node_pool.go, duplocloud/resource_duplo_rds_instance.go, duplosdk/rds_instance.go
Allowing storage_type if empty for aurora dbs. Added un staged changes related to cluster
- Added un staged  code related to cluster update
- Updated storage_type allow logic in customdiff function
- ...
___
enhancement, bug fix
___
- Enhanced the RDS instance update logic to handle Aurora DB clusters separately by appending "-cluster" to the `DBInstanceIdentifier`.
- Added a new function `UpdateDBClusterPerformanceInsight` to support performance insights updates for DB clusters.
- Modified storage type validation to allow empty values, specifically for Aurora DBs.
___
<tr>
<td> …
=> Duplo 21203 Performance Insight Regression

CHANGELOG.md, duplocloud/resource_duplo_rds_instance.go
Ignore aurora type compatibility with performance insights if performance insights is not enabled
- Ignore aurora type compatibility with performance insights if performance insights is not enabled
No
Incompatible perf insights aurora db size and perf insights enabled
Incompatible perf insights aurora db size and perf insights disabled
Compatible aurora db size with perf insights enabled
Compatible aurora db size with perf insights disabled
___
Bug fix
___
- Added logic to check if performance insights are enabled before applying Aurora type compatibility validation.
- Modified the validation function to prevent errors when performance insights are not enabled.
- This change ensures that the system only validates performance insights compatibility for Aurora …
=> DUPLO-21171 hotfix: apply aurora perf insights validation only if performance insights is enabled

CHANGELOG.md, docs/resources/rds_instance.md, docs/resources/rds_read_replica.md, duplocloud/resource_duplo_rds_instance.go, duplocloud/resource_duplo_rds_read_replica.go
Validating Diff for performance insights. Updated documentation
Added diffsupressfunction on performance insights
- Validating diff based on enabled key on performance insights 
- ...
___
___
- Added `DiffSuppressFunc` to suppress diffs for `performance_insights` when disabled in RDS instance and read replica schemas.
- Modified logic to always set `performance_insights` state, regardless of enablement status.
- Updated documentation to specify that the retention period for DocumentDB is 7 days.
- Enhanced descriptions and added a new function `suppressIfPerformanceInsightsDisabled` to handle suppression logic.
___ …
=> DUPLO-21209 DUPLO-21302

CHANGELOG.md, docs/resources/rds_read_replica.md, duplocloud/resource_duplo_rds_read_replica.go, examples/resources/duplocloud_rds_read_replica/resource.tf
Because aurora db performance insights is currently managed at cluster scope, there is no point having performance insights configurations be allowed for such engine types. This may change in the future if we decide to support instance level management for performance insights in aurora engine type instances.
- Prevents creating new aurora read replicas with performance insight configuration set 
- Prevents adding performance insight configuration as an update to an existing aurora read replica
No
plan
result
___
Bug fix, Documentation
___
- Added validation to prevent Aurora read replicas from having performance insights configurations, as these are managed at the cluster level.
- Updated documentation and examples to reflect changes in performance insights …
=> DUPLO-21304 fix: force rds replicas not to have perf insight configuration when they belong in an aurora cluster

CHANGELOG.md, docs/resources/gcp_sql_database_instance.md, duplocloud/resource_duplo_gcp_sql_database.go, duplosdk/gcp_sql_database.go
For `duplocloud_gcp_sql_database_instance` resource, the Duplo backed is updated to generate an array of ip_address, but this resource expects it to be a string. I have made the required changes for that.
- ...
- ...
- ...
___
___
- Updated the `duplocloud_gcp_sql_database_instance` resource to handle `ip_address` as a list of strings, allowing for multiple IP addresses.
- Improved formatting and corrected typos in the `database_version` field description.
- Updated documentation to reflect changes in the `ip_address` field and corrected typos.
- Documented changes in the CHANGELOG.
___
<tr>
<td> …
=> gcp cloud sql resource update

CHANGELOG.md, docs/resources/rds_read_replica.md, duplocloud/resource_duplo_rds_instance.go, duplocloud/resource_duplo_rds_read_replica.go, examples/resources/duplocloud_rds_read_replica/resource.tf
Fixed aurora db updation for performance insights state and plan issues
Fixed plan issues, 
Fixed replica performance insights issue, 
Updated doc example
- Fixed logic at read replica's create and update context for aurora cluster performance insights
- Fixed plan issues
- updated documentation
- ...
___
___
- Enhanced the RDS instance and read replica schemas by adding `DiffSuppressFunc` to suppress changes when Performance Insights is disabled.
- Improved validation logic for Aurora DB configurations to ensure correct application of Performance Insights settings.
- Updated documentation and examples to reflect changes in Performance Insights configuration, providing clearer guidance on …
=> DUPLO-21304 DUPLO-21209 Aurora/v2: replica tries to set value as nil for inplace update and inplace update fixes

duplosdk/aws_mwaa_environment.go
DUPLO-21234: fix tf regression, terraform assume delete message is null
- parse delete response
- ...
- None
=> DUPLO-21234: [Develop]:TF:Airflow: Getting error for resource 'duplocloud_aws_mwaa_environment' on destroy

duplocloud/resource_duplo_azure_redis_cache.go, duplosdk/azure_redis_cache.go
Fix for redis cache creation in private network
Added attribute to disable public access
- Introduced missing attribute PublicNetworkAccess
- Hardcoded PublicNetworkAccess as Disabled based on UI design
- ...
=> DUPLO-21253 

CHANGELOG.md, duplocloud/resource_duplo_tenant.go, duplocloud/utils.go
Added validation for tenant name for gcp cloud
Restricting tenant creation for gcp cloud if tenant name contains google key word in `duplocloud_tenant` resource
- Implemented validation on tenant name for cloud=3 (gcp) to restrict use of google keyword
- ...
- ...
___
___
- Implemented validation to restrict tenant creation in GCP cloud if the tenant name contains the keyword 'google'.
- Defined a constant `GCP_CLOUD` to represent the GCP cloud identifier.
- Updated `CHANGELOG.md` to document the new validation feature.
___
<tr>
<td>
<details> …
=> DUPLO-17188 TF:GCP: allowed to create tenant with google in it

duplocloud/resource_duplo_rds_instance.go
RDS regression fix
Fixed nil pointer exception
- Added a check on storage_type if value exist before converting it from interface to string in validateRDSParameters function
- ...
- ...
=> DUPLO-25412 [Develop] TF: RDS: Plan failed with an error "terraform-provider-duplocloud plugin crashed"

duplocloud/resource_duplo_s3_replication.go
Fix for Update of 'timeouts' shows no changes and not getting updated
Added resource availablity function at create and delete context
- Added function which retries till resource is available based on context time
- ...
=> TF: S3: Replication: Update of 'timeouts' shows no changes and not getting updated

duplocloud/data_source_duplo_aws_ssm_parameter.go, duplocloud/data_source_duplo_aws_ssm_parameters.go
Fix for assigning masked secure string from ssm parameter to other env map resources
Fixed datasource duplocloud_aws_ssm_parameter secure value assignment to state file
- First assigned value to state file and then explicitly masked for log output
- ...
- ...
=> DUPLO-25915 TF provider: SSM data source cannot be used to retrieve secure ssm value 

duplocloud/resource_duplo_s3_replication.go
Add proper validation for rule name for terraform code
- Validation function added which will validate name. Only alphabets, digits, underscores, and hyphens are allowed.
=> issueFix: DUPLO-25454: TF: S3: Replication: Add validation for rule name 

duplocloud/resource_duplo_s3_replication.go
Removed update context
Update not supported , removed update context
- Made rule and sub attribute force new and removed update context
- ...
=> Duplo 25436 TF: S3: Replication: Update of 'Delete marker replication' shows no changes and DUPLO-25447

duplocloud/resource_duplo_s3_replication.go
fixed storage class tfstate attribute set issue
Fixed storage_class is not getting set for resource 'duplocloud_s3_bucket_replication'
- Added missing attribute initialization in create context
- ...
- ...
=> DUPLO-25434 TF: S3: Replication: Storage class is not getting set for resource 'duplocloud_s3_bucket_replication'

docs/resources/asg_profile.md, examples/resources/duplocloud_asg_profile/resource.tf
Add an example block for secondary volume in example usage of duplocloud_asg_profile (Resource)
- Added example block for secondary volume in example of duplocloud_asg_profile (Resource)
=> DUPLO-25619: DOC:TF: ASG: Add example block for secondary volume in example usage of duplocloud_asg_profile (Resource)

duplocloud/resource_duplo_gcp_infra_maintenance_window.go
Missing Scope attribute in response under exclusion for duplocloud_gcp_infra_maintenance_window
- v.Scope != "": This checks whether v.Scope is not an empty string, which is the default value for an uninitialized string in Go.
- If v.Scope is an empty string, set a default value in the mp map.
=> DUPLO-25372: Missing Scope attribute in response under exclusion

duplocloud/resource_duplo_aws_mwaa_environment.go
DUPLO-26078: add new airflow version 2.10.1
- add new airflow version 2.10.1
- none
=> DUPLO-26078: add new airflow version 2.10.1

duplocloud/diff_utils.go, duplocloud/resource_duplo_tenant_config.go
fixed ordering diff for duplocloud_tenant_config
- Added diff suppress function to suppress diff if order in list has change
- ...
- ...
==========================
After reordering
==========================
After change
=> fixed ordering diff for duplocloud_tenant_config

docs/resources/gcp_infra_maintenance_window.md, duplocloud/resource_duplo_gcp_infra_maintenance_window.go
Made scope optional and added default value to scope for duplocloud_gcp_infra_maintenance_window resource
- ...
- ...
- ...
=> DUPLO-25372 

docs/resources/asg_profile.md, docs/resources/aws_host.md, docs/resources/gcp_infra_security_rule.md, docs/resources/gcp_tenant_security_rule.md, duplocloud/resource_duplo_gcp_infra_security_rule.go, duplocloud/validators.go, examples/resources/duplocloud_gcp_infra_security_rule/resource.tf, examples/resources/duplocloud_gcp_tenant_security_rule/resource.tf
…
Add support for multiple ports and protocols for gcp sg rule
Added support for multiple port and protocol. Added validation for duplicate source_ranges for duplocloud_gcp_tenant_security_rule and duplocloud_gcp_infra_security_rule resources
- Updated schema for ports and protocols. 
- Updated code to set and get ports and protocols
- Added duplicate check validation for source_ranges
- updated example and documentation
- ...
=> DUPLO-26458 TF:GCP:Security Rule: Add support for multiple ports and protocols

duplocloud/resource_duplo_gcp_infra_security_rule.go
Validation for IP protocol number
Added validation to service_protocol to except number from 0-255
- Added regex validation for number between 0-255
- ...
- ...
=> DUPLO-26483 TF:GCP:Security Rule: Add validation for 'IP protocol number'

docs/resources/gcp_infra_security_rule.md, docs/resources/gcp_tenant_security_rule.md, duplocloud/resource_duplo_gcp_infra_security_rule.go
GCP security rule bug fixes
TF:GCP:Security Rule: TF should have 'ports_and_protocols' as 'All' in .tfstate file when 'all' is defined along with other type of protocols
TF:GCP:Security Rule: ports_and_protocols filed is blank in .tfstate when service_protocol = "all"
DOC:TF:GCP:Security Rule: Correct 'ports_and_protocols' as a required field
1. Not allowing other service protocol to be requested along with all 
2. all service protocol is getting set in appropriate field
3. documentation update
- Added logic to throw error if any other service protocol is mentioned with all
- Documentation updated
- ...
=> DUPLO-26485 DUPLO-26486 DUPLO-26488

docs/resources/azure_availability_set.md, duplocloud/resource_duplo_azure_availability_set.go
TF:Availability Set: Make 'sku_name' , 'update_domain_count' and 'fault_domain_count' as optional fields
TF: Availability Set: Define default values for fields  'update_domain_count' and 'fault_domain_count' and sku_name
DOC:TF:Availability Set: Need to make changes in document for resource 'duplocloud_azure_availability_set'
TF: Availability Set: Add validation for field 'name' for resource 'duplocloud_azure_availability_set'
TF: Availability Set: Add count limit validation for field 'platform_update_domain_count' and 'platform_fault_domain_count
TF: Availability Set: TF shows forces replacement for name when re-plan without any modification in code
TF: Availability Set: TF should not allow invalid sku_name and throw user friendly error
TF: Availability Set' Change abbreviation for …
=> DUPLO-26671 DUPLO-26672 DUPLO-26673 DUPLO-26675 DUPLO-26679 DUPLO-26683 DUPLO-26684 DUPLO-26686

docs/resources/asg_profile.md, docs/resources/aws_host.md, duplocloud/resource_duplo_aws_host.go
made values optional for taints
made values optional for taints in duplocloud_aws_host resource
- made values optional for taints
- documentation update
- ...
=> DUPLO-26665 TF:EKS: Value should be optional field for taints

docs/resources/gcp_infra_security_rule.md, docs/resources/gcp_tenant_security_rule.md, duplocloud/resource_duplo_gcp_infra_security_rule.go
Documentation update
- Documentation update
- ...
- ...
=> Duplo 26704 DOC:TF:Security Rule: 'sctp' protocol is missing in schema of ports_and_protocols

duplocloud/resource_duplo_rds_instance.go, duplocloud/resource_duplo_rds_read_replica.go, duplosdk/rds_instance.go
[TF] Creating an RDS with name starting with duplo fails
refer images from 
https://github.com/duplocloud-internal/duplo/pull/3541
- rds add validation for duplo prefix
- do not allow double prefix
- ...
=> [TF] Creating an RDS with name starting with duplo fails

docs/resources/ecache_instance.md, duplocloud/resource_duplo_ecache_instance.go
Fix for supported replica count for ecache instance
Added replica validation restricted to 6 for duplocloud_ecache_instance resource
- added replica validation restricted to 6
- ...
- ...
=> DUPLO-26437 TF: Resource 'duplocloud_ecache_instance' should not allow replicas more than 6 for Redis and should throw user friendly validation error

duplocloud/resource_duplo_k8_ingress.go
Host field in rule block of duplocloud_k8_ingress doesnt show diff on change
Fixed non removal of host field in rule block of ingress resource
- Removed compute attribute fro host field of duplocloud_k8_ingress resource
- ...
- ...
=> DUPLO-26030 Ingress `host` property of rules can't be removed in Terraform

docs/data-sources/asg_profiles.md, docs/resources/aws_host.md, duplocloud/resource_duplo_aws_host.go
Removed irrelevant field
Removed encrypt_disk field from duplocloud_aws_host resource
- Removed encrypt_disk field from duplocloud_aws_host
- Updated document
- ...
=> Duplo-26128 Terraform always recreates duplocloud_aws_host when encrypt_disk is true

docs/resources/aws_sqs_queue.md, duplocloud/resource_duplo_aws_sqs_queue.go
Fixed name length of sqs to 80
Fixed name length of to 80 duplocloud_aws_sqs_queue
- Updated regex validation for duplocloud_aws_sqs_queue
- ...
=> DUPLO-29246 SQS Queue Name limited characters on 0.10.54

docs/resources/aws_sqs_queue.md, duplocloud/resource_duplo_rds_instance.go
Restricting parameter_group_name for document db
Not allowing to set parameter_group_name for document db for duplocloud_rds_instance resource
- Added validation to check supported parameter group for a dbtype
- ...
- ...
=> DUPLO-29275 TF:RDS: .tfstate file contains 'DB parameter_group_name' for DocumentDB

docs/resources/rds_instance.md, templates/resources/rds_instance.md.tmpl
Fixed Typo in Documentation and updated example
- Documentation fix
- ...
- ...
=> DUPLO-29307  Doc:TF: Correct typo in document and add parameter_group_name field for read replica in case of standalone instance

docs/resources/ecache_instance.md, duplocloud/resource_duplo_ecache_instance.go
Fix for number of shards not getting set
Added validation on number of shards using custom diff for duplocloud_ecache_instance
- number of shards is only applicable if cluster mode is enabled, Add validation to check if number of shards is set only if enable_cluster_mode is set to true
- updated documentation
- ...
=> DUPLO-29242 TF: Elasticache redis allows non-cluster mode creation with number_of_shards = 1 which causes the resource to become not able to update

docs/resources/aws_elasticsearch.md, duplocloud/resource_duplo_aws_elasticsearch.go
Add TLS 1.2 requirement for govcloud setups to the docs for opensearch useLatestTlsCipher property
- read description
No
=> DUPLO-29614 docs: add opensearch TLS 1.2 requirement for govcloud environments to documentation

duplocloud/resource_duplo_aws_elasticsearch.go
EBS to Non EBS update fix
Updated validation for storage size check for ebs and non ebs
- Updated validation 
- ...
- ...
=> Duplo 29713 TF: OpenSearch: Not able to edit EBS storage type to Non EBS storage type

duplocloud/version_utils.go
Fixed regex to evaluate version comparision for storage_type
Fix for regex failing to fetch version string of type 14, 14.0 patterns while comparing the version
- Updated regex logic
- ...
- ...
=>  DUPLO-26301 TF:RDS: Customer reporting that terraform plan fails when this is already updated

docs/resources/duplo_service_lbconfigs.md, duplocloud/resource_duplo_lbconfigs.go
Added support for backend protocol for ALB load balancer
- Changed backend_protocol_version from computed to optional
- Added validation for backend_protocol_version.
- Documentation updated
- ...
=> DUPLO-19147 TF Provider : Support for Backend protocol version in ALB

duplocloud/resource_duplo_gcp_k8_node_pool.go, duplosdk/gcp_node_pools.go
Fixed diff issue for taints  which gcp adds explicitly
- Added map that holds taint effects explicitly to skip setting such taints
- Added polling function 
- ...
=> DUPLO-26807 TF: Node Pool: re-plan and apply is failing for resource 'duplocloud_gcp_node_pool (Resource)'

docs/resources/k8s_cron_job.md, docs/resources/k8s_job.md, duplocloud/schema_k8s_pod_spec.go, duplocloud/structures_k8s_pod.go
mode value conversion bug fix
Empty mode value throws conversion error to int empty string not getting converted to 0, added check for empty string for duplocloud_k8s_cron_job resource
- Empty mode value throws conversion error to int empty string not getting converted to 0, added check for empty string
- 
- ...
=> DUPLO-29957 [TF] k8_cron_job mode field value conversion throws error

docs/data-sources/k8s_cron_job.md, docs/data-sources/k8s_job.md, docs/resources/k8s_cron_job.md, docs/resources/k8s_job.md, duplocloud/resource_duplo_k8s_cron_job.go, duplocloud/resource_duplo_k8s_job.go, duplosdk/k8s_cron_job.go, duplosdk/k8s_job.go
support for allocation tags field
support for allocation tags field for duplocloud_k8s_cron_job and duplocloud_k8s_job resource
- support for allocation tags field
- updated documentation
- ...
=> DUPLO-29963 Support for allocation tags field

duplocloud/resource_duplo_rds_instance.go
Make storage type force replace for rds instance
Made storage_type field force replace for duplocloud_rds_instance
- Made storage_type force replace
- ...
- ...
=> DUPLO-25455  TF:RDS: Updating Storage type should show force replacement of resource

duplocloud/resource_duplo_lbconfigs.go
Added protocol validation for every type of lb
Added protocol validation for every type of load balancer in duplocloud_duplo_service_lbconfigs resource
- Added validation for protocol field based on lb_type
- ...
- ...
=> DUPLO-30382 TF Provider: Fix validation for protocol in duplocloud_duplo_service_lbconfigs

Makefile, duplocloud/resource_duplo_tenant.go, duplocloud/resource_duplo_tenant_test.go
Throwing proper error based on allow_deletion and delete_protection setting in duplocloud_tenant resource
- ...
- ...
- ...
=> DUPLO-29758 Terraform provider doesn't delete tenant created with "allow_deletion" set to false

docs/resources/duplo_service_lbconfigs.md, examples/resources/duplocloud_duplo_service_lbconfigs/resource.tf
Document update for duplocloud_duplo_service_lbconfigs
- Added example with backend_protocol_version usage
- ...
- ...
=> DUPLO-30397 TF:DOC: Add usage example with 'Backend protocol version' for resource 'duplocloud_duplo_service_lbconfigs'

docs/resources/duplo_service_lbconfigs.md, duplocloud/resource_duplo_rds_instance.go
Change done in parameter_group_name field 
Made parameter_group_name field updatable in duplocloud_rds_instance resource
- Removed compute attribute
- Added diff suppress function
- ...
=> DUPLO-30500 [TF] Changes to parameter group is not reflected after the RDS is already created

duplocloud/resource_duplo_lbconfigs.go, duplocloud/utils.go
Backward Compatibility 
Allowing protocol and backward_protocol to be passed irrespective of case
- Allow ignore case in validation
- DiffSuppress function to ignore change based on case
- Passing protocol and backend_version_protocol to request in uppercase
- ...
=> DUPLO-30525 LB Config protocol attribute validation is breaking backward compatibility

duplocloud/resource_duplo_k8_secret.go
filter default secrete label keys
Added filter to filter out default labels in secret_labels field if not specified in duplocloud_k8_secret
- Added logic to filter out default lable if not mentioned
- ...
- ...
=> DUPLO-29744 TF: Resource 'duplocloud_k8_secret' shows update in place for labels for re-plan without any modification

docs/resources/duplo_service_lbconfigs.md, duplocloud/resource_duplo_lbconfigs.go
Backward compatibility fix
Removed force new and default value attribute and added computed attribute for the optional backward_protocol_version filed of duplocloud_duplo_service_lbconfigs.
Removed validation to check if backward_protocol_version is passed if lb_type is ALB (1)
- Removed force new ,default value added compute true to backward_protocol_version
- Removed validation logic to check backward_protocol_version is passed if lb_type=1
- ...
=> DUPLO-30649 [TF] Load balancer configuration : make backend_protocol_version optional and computed for backward compatability

duplocloud/resource_duplo_ecache_instance.go, duplosdk/ecache_instance.go
- The computed attribute endpoint and host are not set if ecache cluster mode is enabled.
- The computed attribute set for both clustered and non-clustered redis caches.
-
=> DUPLO-30732 : Bug Fix: The computed attribute endpoint and host are not set if ecache cluster mode is enabled.

duplocloud/resource_duplo_service.go
Force replace service when agent platform is changed
- made agent_platform force new for duplocloud_duplo_service
- ...
- ...
=> DUPLO-16771 TF: Force replacement of resource should be shown for `duplocloud_duplo_service` when `agent_platform` value is updated

docs/resources/duplo_service_lbconfigs.md, examples/resources/duplocloud_duplo_service_lbconfigs/resource.tf
Example update
Example update for duplocloud_duplo_service_lbconfigs resource in health_check block due to fault for timeout > interval
- Added lower value to timeout than interval
- Document updated
- ...
=> DUPLO-30485 DOC:TF:lbconfig: Correct the example usage for resource 'duplocloud_duplo_service_lbconfigs'

duplocloud/resource_duplo_lbconfigs.go
Validation fix
Updated validation boundary value.
- Updated validation for health_check.timeout from 2 - 100  to 2 - 120
- ...
- ...
=> DUPLO-30487 TF:lbconfig: HealthCheckTimeoutSeconds range should be between 2–120 seconds

duplocloud/resource_duplo_gcp_sql_database.go, duplocloud/utils.go
Fixed Default label usage and context out issue on update
Added default label to filter , added waituntilunavailable function to resolve context timeout
- Added duplo-tenant label key to filter
- Added waituntilunavailable with timeout of 5 min which will poll for 5 min to check status has change from runnable to non runnable state on modifying
- ...
=> DUPLO-30973 TF: GCP SQL Takes forever to change label I didn't change

duplocloud/resource_duplo_helm_repository.go, duplosdk/duplo_helm.go
Bug fix
Fixed helm repository creation with optional field type and provider for resource duplocloud_k8_helm_repository
- Added omitempty to field and provider attribute in helm repository model
- ...
- ...
=> DUPLO-31001 Helm Repository Fails to create when Optional Fields 'helm_provider' and 'type' are not provided

docs/resources/ecache_instance.md, docs/resources/ecs_service.md, duplocloud/resource_duplo_ecs_service.go, examples/resources/duplocloud_ecs_service/resource.tf
Support for EC2 capacity
Allowed passing host as capacity provider created with agent platform as ecs This PR does the following:
* Removed validation on capacity_provider, BE has validation in place to check if correct host is passed
* Updated document with example
* [ ✔︎] Manually, on a remote test system
* ...
=> DUPLO-30481 TF: AWS:Support EC2 Capacity provider for ECS

duplocloud/resource_duplo_lbconfigs.go
TCP, UDP, TLS protocol support for  Target Group
Validation fix
- Allowed tcp,udp,tls for lb_type=7 along with http and https protocol
- ...
- ...
=> DUPLO-31151 [TF] support TCP, UDP and TLS protocol for Target Group LB type

docs/resources/gcp_node_pool.md, duplocloud/resource_duplo_gcp_k8_node_pool.go, examples/resources/duplocloud_gcp_node_pool/resource.tf
Fixed usage
Diff fix
Fix for variable setting to state error
- Document update for NODE_POOL_UPDATE_STRATEGY_UNSPECIFIED update strategy usage
- Made taints field computed
- fixed setting fields to state
- ...
=> DUPLO-30932 duplocloud_gcp_k8_node_pools thrwoing error on upgrade_settings startegy.

duplocloud/resource_duplo_rds_instance.go, duplosdk/rds_instance.go
Fix for Deletion Protection value not getting set
Fixed deletion_protection not getting set for rds cluster in duplocloud_rds_instance resource
- Added AWS pass through API to fetch deletion protection value
- Calling AWS pass through APi if db is cluster db
- ...
=> DUPLO-31221 TF resource duplocloud_rds_instance always shows diff for deletion_protection.

docs/resources/asg_instance_refresh.md, docs/resources/duplo_service_lbconfigs.md, docs/resources/ecache_instance.md, duplocloud/resource_duplo_ecache_instance.go
Document update for duplocloud_rds_instance 
- Added instance type index for valkey
- ...
- ...
=> DUPLO-30317 DOC:TF:ValkeyCache: Add usage example for cache_type = Valkey

docs/resources/azure_mssqldb_retention_backup.md, duplocloud/resource_duplo_azure_mssqldb_retention_backup.go
Made retention_backup required field for duplocloud_azure_mssqldb_retention_backup
- .Made retention_backup required field.
- ...
- ...
=> DUPLO-31364 Doc:TF: The retention_backup field is mentioned as optional in the documentation, but it should be required field

Makefile, duplocloud/resource_duplo_asg_profile.go, duplocloud/resource_duplo_aws_host.go, duplocloud/resource_duplo_aws_host_test.go, duplosdk/asg.go, duplosdk/client_with_retry_rate_exceeded.go, duplosdk/native_hosts.go
Retry mechanism for asg and host resource
Retries add for get api for 400 errors in duplocloud_aws_host and duplocloud_asg_profile
- Retires added for asg and host get apis
- ...
- ...
=> DUPLO-30689 Error: context deadline exceeded for ASG and EC2

duplocloud/resource_duplo_ecache_instance.go
Ecache instances are prefixed with `duplo-` instead of `duploservices-`
- fixes wrong prefix
No
In UI:
Creating
Created with proper prefix
=> DUPLO-31508 fix: cherrypick to 11.9

duplocloud/resource_duplo_infrastructure.go
Fixed bug for resource not waiting infra to be deleted if wait_until_delete is enabled
Added polling function waitForResourceToBeMissingAfterDelete inside if wait_until_delete is enabled block
- Added polling function waitForResourceToBeMissingAfterDelete inside if wait_until_delete is enabled block 
- ...
- ...
=> DUPLO-31538 [TF] Infrastructure resource should wait till destroy of infra resource if wait_until_deleted is true

docs/resources/aws_launch_template.md, duplocloud/resource_duplo_aws_launch_template.go
Setting latest version to source version if version not provided
Setting latest version to source version if version not provided duplocloud_aws_launch_template resource
- Added logic to set latest version to source version if version not provided explicitly
- ...
- ...
=> DUPLO-31503 Not setting the version is causing defaults to be set in the Launch template

docs/resources/asg_instance_refresh.md, duplocloud/resource_duplo_aws_lambda_permission.go, duplosdk/aws_lambda_function.go
Tackle unmarshall issue
Tackling unmarshall issue for duplocloud_aws_lambda_permission resource
- Made schema field attribute changes
- Made read context fixes to set field value
- ...
=> DUPLO-31462 TF: duplocloud_aws_lambda_permission cannot unmarshal string into Go Struct

duplocloud/resource_duplo_tenant_network_security_rule.go, duplosdk/tenant.go
Fix resource destruction after import
Fixed resource getting destroyed after import for duplocloud_tenant_network_security_rule resource
- Set missing description value to description field
- ...
- ...
=> DUPLO-31438 TF: Importing duplocloud_tenant_network_security_rule force adds description

duplosdk/aws_target_group_target_manager.go
Crash fix
Plugin crash fix for duplocloud_aws_target_group_target_register resource
- map value validation
- ...
- ...
=> DUPLO-31520 TF: Target Group: TF throws 'Plugin Crashed' for target type 'instance'

duplosdk/azure_key_vault.go
Added getRetryAPI to deletedVaults api for azure to avoid 400 error. Cause not known BE fix is needed
- ...
- ...
- ...
=> DUPLO-31358  Added retry to DeletedVaults API to avoid 400.

duplocloud/resource_duplo_tenant.go
- Add support for tenant names in uppercase and camelCase formats.
- Add support for tenant names in uppercase and camelCase formats.
- Tenant creation.
- Tenant Plan.
=> DUPLO-31965: Add support for tenant names in uppercase and camelCase formats.

duplocloud/resource_duplo_aws_lambda_function.go, duplocloud/resource_duplo_aws_lambda_permission.go, duplosdk/aws_lambda_function.go
Plugin crash fix
Fixed plugin crash on duplocloud_aws_lambda_permission resource caused due to permission removal outside TF
- Fixed plugin crash
- Handled diff at duplocloud_aws_lambda_function
- ...
=> DUPLO-32856 TF Provider crash with Invalid Memory Address Error

duplocloud/resource_duplo_asg_profile.go
Fixed issue of asg not getting created when lifecycle policy create_before_destroy is used
Updated asg name
- Adding system time to asg name before creation
- 
- ...
=> DUPLO-32577 Terraform - Destroy/Create of ASG doesn't create new asg

duplocloud/resource_duplo_aws_cloudwatch_event_target.go, duplosdk/aws_cloudwatch.go
Unmarshall issue fix
Removed response holding variable
- Post api and delete api not returning any response. Leading to unmarshal issue removed those variable
- Added check for empty response in read context to avoid plugin crash
- ...
=> DUPLO-33110 Terraform fails on Cloudwatch Event Target Creation

docs/resources/gcp_sql_database_instance.md, duplocloud/resource_duplo_gcp_sql_database.go, duplosdk/gcp_sql_database.go
Database flag suport for cloud sql
Added field database_flag in duplocloud_gcp_sql_database_instance resource
- Added database_flag list of object field
- Updated doc
- ...
=> DUPLO-33213 TF: duplocloud_gcp_sql_database_instance  add database_flags support

duplocloud/resource_duplo_ecache_instance.go, duplosdk/ecache_instance.go
Support to update snapshot retention limit
Added update context to update snapshot_retention_limit for duplocloud_ecache_instance resource
- Added update context to update snapshot_retention_limit for redis and valkey
- Added custom validation to not set snapshot_retention_limit for memcache cache type
- ...
=> DUPLO-30548 resource duplocloud_ecache_instance : cannot set snapshot_retention_limit for already existing instance

docs/resources/azure_cosmos_db_account.md, docs/resources/duplo_service.md, duplocloud/data_source_duplo_service.go, duplocloud/resource_duplo_service.go, duplosdk/replication_controller.go, examples/resources/duplocloud_azure_cosmos_db_account/resource.tf, examples/resources/duplocloud_duplo_service/resource.tf
Support for app name for service resource
Added new field app_name in duplocloud_duplo_service
- duplocloud_duplo_service resource schema change added new field app_name
- .updated example and doc
- ...
=> DUPLO-32904 TF: Add field app_name

duplosdk/asg.go
removed omitempty from is IsClusterAutoscaled for duplocloud_asg_profile field
- ...
- ...
- ...
=> DUPLO-35510 TF Handle change for ASG profile serialisation issue

docs/resources/azure_mssql_server.md, duplocloud/resource_duplo_azure_mssql_server.go
Document update for duplocloud_azure_mssql_server resource
- ...
- ...
- ...
=> DUPLO-35523 DOC:Azure:MSSQL Server: For resource duplocloud_azure_mssql_server the values for administrator_type  field are not mentioned

duplocloud/provider_test.go, duplocloud/resource_duplo_gcp_k8_node_pool.go, duplocloud/resource_duplo_infrastructure.go, duplocloud/resource_duplo_plan_settings.go, duplocloud/resource_duplo_tenant.go, duplocloud/resource_duplo_tenant_config.go, duplosdk/infrastructure.go, internal/duplosdktest/emulator.go
Added 404 handling
Exception handling of 404 to reset id
Change of API for infrastructure get api
- Changed infrastructure get api to v3
- .404 error handling for read and delete context for 
duplocloud_plan_settings 
duplocloud_infrastructure
duplocloud_tenant
duplocloud_tenant_config
duplocloud_gcp_node_pool resources
- ...
=> TF handle 404 error and set resource id to empty to avoid terraform termination

duplocloud/resource_duplo_ecache_instance.go
Fixed name length validation bug
Removed GetResourceName function . This was just a logical validation that does not effect with which name resource is created.
Name is always getting created without tenant name. Wont effect any previously created ecache
- Added logic to create fullName as "duplo-"+name to validate length
- ...
- ...
=> DUPLO-35618 duplocloud_ecache_instance throws error exceeds allowable ecache name length 40

docs/data-sources/ecs_task_definition.md, docs/resources/ecs_task_definition.md, duplocloud/resource_duplo_ecs_task_definition.go
Document Update for duplocloud_ecs_task_definition
- ...
- ...
- ...
=> DUPLO-35661 TF Doc: ECS: The duplocloud_ecs_task_definition resource doc should mention the requires_compatibilities values

duplocloud/data_source_duplo_infrastructure.go
Plugin crash fix
Added missing tenant_id validation for datasource duplocloud_infrastructure
- added UUID validation for tenant_id field
- ...
- ...
=> DUPLO-31839 Terraform v0.11.10 provider crash with incorrect datasource config

docs/resources/aws_load_balancer_listener.md, duplocloud/resource_duplo_tenant_aws_lb_listeners.go
Plugin crash fix for duplocloud_aws_load_balancer_listener resource
- ...
- ...
- ...
=> DUPLO-36798 Plugin crashes when default_actions field is empty and shows invalid error message when not provided

duplocloud/resource_duplo_infrastructure.go
Fixed cluster_ip_cidr not getting set for duplocloud_infrastructure resource
- ...
- ...
- ...
=> DUPLO-36797 [TF] : After doing terraform import cluster_ip_cidr and some settings went missing from terraform state

docs/resources/ecache_associate_global_secondary_cluster.md, duplocloud/duplocloud_ecache_associate_global_secondary_cluster.go, duplocloud/resource_duplo_ecache_global_datastore.go, duplosdk/ecache_instance.go, examples/resources/duplocloud_ecache_associate_global_secondary_cluster/resource.tf
REmoved port from duplocloud_ecache_associate_global_secondary_cluster
- ...
- ...
- ...
=> DUPLO-35622

duplocloud/resource_duplo_gcp_k8_node_pool.go, duplocloud/resource_duplo_infrastructure.go, duplocloud/resource_duplo_plan_settings.go, duplocloud/resource_duplo_tenant.go, duplocloud/resource_duplo_tenant_config.go, duplocloud/resource_duplo_user_tenant_access.go
Error format updated
Updated error format for 
duplocloud_infrastructure 
duplocloud_plan_settings 
duplocloud_tenant 
duplocloud_tenant_config 
duplocloud_user_tenant_access
duplocloud_gcp_node_pool
- Error: Duplocloud resource <resource-id>
<API error>
- ...
- ...
=> DUPLO-36938 TF:  Add resource id in the error message along with uniform error message if resource already exists

docs/resources/ecache_associate_global_secondary_cluster.md, docs/resources/ecache_instance.md, docs/resources/gcp_node_pool.md, duplocloud/duplocloud_ecache_associate_global_secondary_cluster.go, duplocloud/resource_duplo_ecache_instance.go, duplosdk/ecache_instance.go, examples/resources/duplocloud_ecache_associate_global_secondary_cluster/resource.tf
KMS and Auth token support 
Added support of kms field and auth token field to duplocloud_ecache_associate_global_secondary_cluster
- Schema updated
- Doc and example updated
- ...
=> DUPLO-36977 TF KMS support for global redis cluster

duplocloud/resource_duplo_tenant_aws_lb_listeners.go
Bug fix
Field not getting set on import for duplocloud_aws_load_balancer_listener
- fix for default actions field not getting set while importing loadbalancer listener resource
- ...
- ...
=> DUPLO-37160 TF: default actions field not getting set on import for duplocloud_aws_load_balancer_listener resource

duplocloud/resource_duplo_azure_tenant_key_vault_secret.go, duplosdk/azure_key_vault.go
Added retry to get api and sleep to avoid API crash
- ...
- ...
- ...
=> DUPLO-37001 Hitting 400 when deleting keyvault secrets more than 2 at once through TF

docs/resources/aws_sqs_queue.md, duplocloud/resource_duplo_aws_sqs_queue.go, duplosdk/aws_sqs.go
New field support
Added new field receive_wait_time_seconds for resource duplocloud_aws_sqs_queue
- CUR operation support for receive_wait_time_seconds field
- Document updated
- ...
=> DUPLO-36676 TF: support receive_wait_time_seconds in duplocloud_aws_sqs_queue

duplocloud/resource_duplo_tenant_aws_lb_listeners.go
Error logic handling
Error logic handling for duplocloud_aws_load_balancer_listener resource
- Moved logic handling in create context
- ...
- ...
=> DUPLO-37506 Error: Either 'target_group_arn' or 'default_actions' block must be specified

duplocloud/resource_duplo_aws_cloudwatch_event_target.go
Bug fix
Fixed value passing issue
- RoleArn value initialisation missing fixed.
- ...
- ...
=> DUPLO-37557 TF: duplocloud_aws_cloudwatch_event_target does not send RoleArn if specified for create (but api accepts this)

docs/resources/asg_profile.md, docs/resources/aws_host.md, duplocloud/resource_duplo_aws_host.go
Enum representation fix
- Updated document for keypair_type for its representation
- ...
- [✔︎ ] Manually, on my local system
- ...
=> DUPLO-37738 keypair_type in aws_host resource is wrong

duplocloud/resource_duplo_ecs_task_definition.go
Fixed no change issue
- Filter and setting the field since AWS auto manages the requires_compatibilities
- ...
- ...
=> DUPLO-36573 TF: Updating requires_compatibilities field does not work, show no changes

docs/resources/gcp_sql_database_instance.md, duplocloud/resource_duplo_gcp_sql_database.go
Bug fix
Fixed diff issue caused by default value
- ...
- ...
- ...
=> DUPLO-37800 GCP: Cloud SQL: Backward Compatibility shows differences for edition field
