- docs/resources/aws_host.md
- duplocloud/resource_duplo_asg_profile.go
- duplocloud/resource_duplo_aws_host.go
- duplosdk/tenant_aws_cloud_resources.go
- Allocation tags support for ASG profile.
- Description for minion tags is updated with allocation tag example.
> Allocation tags support for ASG profile.

- docs/resources/aws_lambda_function.md
- duplocloud/resource_duplo_asg_profile.go
- duplocloud/resource_duplo_aws_host.go
- duplocloud/resource_duplo_aws_lambda_function.go
- duplosdk/aws_lambda_function.go
Tags and Layers attribute support in duplo lambda function resource..
> Tags and Layers attribute support in duplo lambda function resource.

- duplocloud/resource_duplo_tenant_network_security_rule.go
- duplosdk/tenant.go
Tenant SG network rule CIDR issue is fixed.
> Tenant SG network rule CIDR issue is fixed.

- duplocloud/data_source_duplo_plan_cert.go
- duplocloud/data_source_duplo_plan_image.go
- Crash issue is fixed for the plan certificate and image.
> Crash issue is fixed for plan certificate and image.

- docs/resources/rds_instance.md
- duplocloud/resource_duplo_rds_instance.go
Document db delete protection issue fixed.
> Document db delete protection issue fixed.

- duplosdk/azure_redis_cache.go
Redis cache issue of empty subnet id is fixed.
> Redis cache issue of empty subnet id is fixed.

- docs/resources/ecache_instance.md
- duplocloud/resource_duplo_ecache_instance.go
- KMS Key Id attribute is added.
> KMS Key Id attribute is added.

- duplocloud/resource_duplo_aws_cloudfront_distribution.go
- duplosdk/aws_cloudfront_distribution.go
- hosted_zone_id is set.
- S3 config OAI is set on update.
- origin_shield is added.
> Cloudfront resource bug fixes.

- duplocloud/resource_duplo_asg_profile.go
> ASG timeout issue is fixed.

- docs/data-sources/duplo_service.md
- docs/data-sources/duplo_services.md
- docs/resources/duplo_service.md
- duplocloud/data_source_duplo_service.go
- duplocloud/resource_duplo_ecs_service.go
- duplocloud/resource_duplo_service.go
- duplosdk/replication_controller.go
- HPA Specs support added in duplo service.
- ECS load balancer config issue fixed.
> HPA Specs support added in duplo service.

- .github/workflows/dev-check.yml
- docs/resources/ecs_service.md
- docs/resources/plan_settings.md
- duplocloud/Utils.go
- duplocloud/resource_duplo_aws_lambda_function.go
- duplocloud/resource_duplo_ecs_service.go
- duplocloud/resource_duplo_plan_settings.go
DUPLO-2983, DUPLO-3066, and DUPLO-2982 fixed.
https://app.clickup.com/t/8655600/DUPLO-2983
https://app.clickup.com/t/8655600/DUPLO-2982
https://app.clickup.com/t/8655600/DUPLO-3066
> DUPLO-2983, DUPLO-3066, and DUPLO-2982 fixed.

- duplocloud/resource_duplo_lbconfigs.go
Classic load balancer ignored from wait logic.
> Classic load balancer ignored from wait logic.

- duplocloud/resource_duplo_rds_instance.go
RDS aurora username and password validation is removed.
> RDS aurora username and password validation is removed.

- docs/data-sources/ecs_task_definitions.md
- docs/resources/rds_instance.md
- duplocloud/resource_duplo_aws_elasticsearch.go
- duplocloud/resource_duplo_rds_instance.go
- duplosdk/rds_instance.go
- KMS Id support in RDS resource.
- Delete protection API changed for Aurora databases.
> KMS id support RDS and Delete protection API changes.

- docs/resources/aws_load_balancer.md
- duplocloud/resource_duplo_aws_load_balancer.go
- duplosdk/tenant_aws_cloud_resources.go
> NLB support added.

- duplocloud/resource_duplo_aws_appautoscaling_policy.go
- duplocloud/resource_duplo_aws_appautoscaling_target.go
> Check for missing Duplo object

- duplocloud/resource_duplo_service_params.go
> WAF bug fix for non AWS platform.

- docs/data-sources/duplo_service.md
- docs/data-sources/duplo_services.md
- docs/resources/duplo_service.md
- duplocloud/data_source_duplo_service.go
- duplocloud/resource_duplo_service.go
Attribute replica_collocation_allowed added for duplocloud_duplo_service resource.
> Fix [#1]()
> DUPLO-4007: Attribute replica_collocation_allowed added for duplocloud_duplo_service resource.

- duplocloud/resource_duplo_infrastructure.go
Subnet naming issue fixed.
> Fix [#1]()
> Subnet naming issue fixed.

- docs/resources/infrastructure.md
- duplocloud/resource_duplo_infrastructure.go
Fix for backward compatibility.
> Fix [#1]()
> Fix for backward compatibility.

- duplocloud/resource_duplo_infrastructure.go
- duplocloud/resource_duplo_infrastructure_subnet.go
- Azure infra issue fixes.
> Fix [#1]()
> Azure infra issue fixes.

- duplocloud/resource_duplo_aws_lambda_function.go
- duplosdk/aws_lambda_function.go
> DUPLO-4153: add container lambda support

- duplocloud/resource_duplo_oci_containerengine_node_pool.go
- duplosdk/oci_containerengine_node_pool.go
Oci Nodepool scale for spark cluster management
IA oci Nodepool  
> Fix [#1]()
> oci manaul nodepool scale

- duplocloud/resource_duplo_oci_containerengine_node_pool.go
- duplosdk/oci_containerengine_node_pool.go
OCI node pool scale
feature 
oci nodepool scale for IA
recreate PR removing
default value for  required "size"
> Fix [#1]()
> oci nodepool scale for IA

- duplocloud/provider.go
- duplocloud/resource_duplo_infrastructure.go
- duplocloud/resource_duplo_infrastructure_setting.go
- duplosdk/infrastructure.go
- examples/infrastructure/main.tf
> DUPLO-3517: support infrastructure settings

- duplocloud/resource_duplo_ecache_instance.go
- duplosdk/ecache_instance.go
> DUPLO-4317: add redis parameter group. fix silent non-update of field.

- duplocloud/resource_duplo_aws_sns_topic.go
- Name issue fix for sns topic.
> Name issue fix for sns topic.

- duplocloud/data_source_duplo_service.go
- duplocloud/resource_duplo_lbconfigs.go
- Issue Fixed - Volume diff.
- Issue Fixed - setting state: Invalid address to set: []string{"name"}
> Bug fixes.

- duplocloud/resource_duplo_tenant.go
DUPLO-4631 : duplocloud_tenant resource should ensure that the tenant actually gets created.
> DUPLO-4631 : duplocloud_tenant resource should ensure that the tenant actually gets created.

- docs/resources/aws_kafka_cluster.md
- duplocloud/resource_duplo_aws_lambda_function.go
- duplocloud/resource_duplo_ecs_service.go
- duplocloud/resource_duplo_kafka_cluster.go
- duplosdk/ecs_service.go
- duplosdk/tenant.go
- duplosdk/tenant_aws_cloud_resources.go
- Add support of python3.9 runtime for lambda resource. (Element5)
- Support transit encryption for kafka resource.
- Implement proper wait logic based on target groups for ecs resource creation. (spotnana)
> DUPLO-4306 : Implement proper wait logic for ecs resource creation.

- docs/data-sources/ecs_service.md
- docs/data-sources/ecs_services.md
- docs/resources/ecs_service.md
- duplocloud/resource_duplo_ecs_service.go
- Computed field index added for ecs and lb.
> Computed field index added for ecs and lb.

- duplocloud/resource_duplo_ecs_service.go
- ECS index field optional to computed.
> ECS index field optional to computed.

- docs/resources/rds_instance.md
- duplocloud/resource_duplo_rds_instance.go
- Aurora DB type (16) is added.
> Aurora DB type (16) is added.

- docs/data-sources/ecs_service.md
- docs/data-sources/ecs_services.md
- docs/resources/ecs_service.md
- duplocloud/resource_duplo_ecs_service.go
- duplosdk/ecs_service.go
- DUPLO-5219: Add support Capacity provider in duplo ECS service.
> DUPLO-5219: Add support Capacity provider in duplo ECS service.

- duplocloud/resource_duplo_asg_profile.go
Wait 3 min after ASG is deleted.
> Wait 3 min after ASG is deleted.

- duplocloud/resource_duplo_aws_api_gateway_integration.go
- Resource `duplocloud_aws_api_gateway_integration` timeout issue fixed.
> Resource `duplocloud_aws_api_gateway_integration` timeout issue fixed.

- duplocloud/resource_duplo_aws_cloudfront_distribution.go
- duplosdk/aws_cloudfront_distribution.go
Cloudfront attribute realtime_log_config_arn and response_headers_policy_id added.
> Cloudfront attribute realtime_log_config_arn and response_headers_policy_id added.

- duplocloud/resource_duplo_plan_configs.go
- duplocloud/resource_duplo_plan_settings.go
- duplosdk/plan.go
- examples/infrastructure/main.tf
> Duplo 5515 safe plan settings apis

- duplocloud/data_source_duplo_k8_secret.go
> DUPLO-5564 fixed.

- docs/data-sources/duplo_service_lbconfigs.md
- docs/resources/duplo_service_lbconfigs.md
- duplocloud/data_source_duplo_service_lbconfigs.go
- duplocloud/resource_duplo_lbconfigs.go
- duplosdk/replication_controller.go
Computed attribute target_group_arn is added for duplocloud_duplo_service_lbconfigs resource.
> Computed attribute target_group_arn is added for duplocloud_duplo_service_lbconfigs resource.

- docs/data-sources/duplo_service_lbconfigs.md
- docs/resources/duplo_service.md
- docs/resources/duplo_service_lbconfigs.md
- duplocloud/data_source_duplo_service.go
- duplocloud/resource_duplo_lbconfigs.go
- duplocloud/resource_duplo_service.go
Computed attribute index for Duplo service and lbconfigs resource.
> Computed attribute index for Duplo service and lbconfigs resource.

- docs/resources/duplo_service_lbconfigs.md
- duplocloud/resource_duplo_lbconfigs.go
- Document changes for resource duplocloud_duplo_service_lbconfigs.
> Document changes for resource duplocloud_duplo_service_lbconfigs.

- duplosdk/aws_cloudfront_distribution.go
- CFD put API changes and removed the ID path variables from URL.
> CFD put API changes and removed path variable from URL.

- duplocloud/data_source_duplo_service_lbconfigs.go
- duplocloud/resource_duplo_lbconfigs.go
- Setting of target group arn is removed.
> Setting of target group arn is removed.

- duplocloud/resource_duplo_k8_ingress.go
- The ingress issue is fixed when the load balancer config is empty.
> Ingress issue is fixed when load balancer config is empty.

- duplocloud/resource_duplo_infrastructure.go
Infra name length limit increased to 30.
> Infra name length limit increased to 30.

- docs/resources/aws_efs_file_system.md
- duplocloud/resource_duplo_service.go
- examples/resources/duplocloud_aws_efs_file_system/import.sh
> DUPLO-6588 fixed : HPA specs not being sent to backend.

- duplocloud/resource_duplo_asg_profile.go
DUPLO-6976: ASG timeout issue fixed when desired count is greater than min count.
> DUPLO-6976: ASG timeout issue fixed when desired count is greater than min count.

- docs/resources/rds_instance.md
- duplocloud/resource_duplo_rds_instance.go
- duplosdk/rds_instance.go
Support attribute db_subnet_group_name for resource duplocloud_rds_instance.
> DUPLO-6518: Support attribute db_subnet_group_name for resource duplocloud_rds_instance.

- duplocloud/resource_duplo_azure_virtual_machine.go
- duplocloud/resource_duplo_lbconfigs.go
- duplosdk/native_hosts.go
> Azure bug fixes

- duplocloud/resource_duplo_tenant_aws_lb_listeners.go
- duplosdk/tenant_aws_cloud_resources.go
- Multiple listener issue fixed when attached to the same target group.
> Multiple listener issue fixed when attached to the same target group.

- docs/resources/aws_batch_compute_environment.md
- duplocloud/resource_duplo_aws_batch_compute_environment.go
- duplocloud/resource_duplo_aws_batch_job_definition.go
- duplosdk/aws_batch.go
- DUPLO-7625, DUPLO-7624 fixed.
> DUPLO-7625, DUPLO-7624 fixed.

- docs/resources/aws_batch_compute_environment.md
- duplocloud/resource_duplo_aws_batch_compute_environment.go
- Document changes for compute environment resource.
> Document changes for compute environment resource.

- duplocloud/resource_duplo_aws_timestreamwrite_database.go
- duplocloud/resource_duplo_aws_timestreamwrite_table.go
- DUPLO-7725, DUPLO-7728 fixed.
> DUPLO-7725, DUPLO-7728 fixed.

- duplocloud/resource_duplo_aws_timestreamwrite_database.go
- duplocloud/resource_duplo_aws_timestreamwrite_table.go
- Resource name validation removed.
> Resource name validation removed.

- docs/resources/duplo_service_params.md
- duplocloud/resource_duplo_service_params.go
- duplosdk/tenant_aws_cloud_resources.go
- TF Provider: Add IdleTimeout to resource duplocloud_aws_load_balancer.
> TF Provider: Add IdleTimeout to resource duplocloud_aws_load_balancer.

- docs/resources/aws_load_balancer.md
- duplocloud/resource_duplo_aws_load_balancer.go
- Attribute idle_timeout supported for duplocloud_aws_load_balancer.
> Attribute idle_timeout supported for duplocloud_aws_load_balancer.

- docs/data-sources/ecs_service.md
- docs/data-sources/ecs_services.md
- docs/resources/ecs_service.md
- duplocloud/resource_duplo_ecs_service.go
- duplosdk/ecs_service.go
TF Provider: Add Idle Timeout support for ECS Application LB.
> TF Provider: Add Idle Timeout support for ECS Application LB.

- duplocloud/resource_duplo_ecs_service.go
- Sleep removed because retry logic added.
> Sleep removed because retry logic added.

- docs/data-sources/asg_profiles.md
- docs/resources/asg_profile.md
- duplocloud/resource_duplo_asg_profile.go
- duplosdk/asg.go
- use_launch_template attribute added for ASG resource.
> use_launch_template attribute added for ASG resource.

- docs/data-sources/k8_secret.md
- docs/data-sources/k8_secrets.md
- docs/resources/k8_secret.md
- duplocloud/data_source_duplo_k8_secret.go
- duplocloud/data_source_duplo_k8_secrets.go
- duplocloud/resource_duplo_k8_secret.go
- duplosdk/k8_secret.go
Reverts duplocloud/terraform-provider-duplocloud#218
> Revert "DUPLO-7949: Use V3 Kubernetes secrets API"

- duplocloud/resource_duplo_tenant_aws_lb_listeners.go
> Listener Bug fix.

- docs/resources/aws_elasticsearch.md
- docs/resources/rds_instance.md
- examples/resources/duplocloud_aws_elasticsearch/resource.tf
- examples/resources/duplocloud_rds_instance/resource.tf
> Update example for RDS and Elastic Search
> Duplo 8445

- duplocloud/resource_duplo_aws_elasticsearch.go
- panic: interface conversion: interface {} is []interface {}, not []string resolved.
> Panic issue resolved.

- docs/resources/azure_virtual_machine.md
- duplocloud/Utils.go
- duplocloud/resource_duplo_aws_cloudfront_distribution.go
- duplocloud/resource_duplo_azure_virtual_machine.go
- Azure virtual machine join domain support added.
> Azure virtual machine join domain support added.

- docs/resources/asg_profile.md
- docs/resources/aws_host.md
- duplocloud/resource_duplo_aws_host.go
- Attribute keypair_type document updates.
> Attribute keypair_type document updates.

- duplocloud/resource_duplo_infrastructure_setting.go
- duplosdk/infrastructure.go
- DUPLO-9383 and DUPLO-9428 fixed.
> DUPLO-9383 and DUPLO-9428 fixed.

- duplocloud/resource_duplo_admin_system_setting.go
> DUPLO-9482 fixed.

- duplocloud/resource_duplo_k8s_secret_provider_class.go
- TF Crash fixed for duplocloud_k8_secret_provider_class.
> TF Crash fixed for duplocloud_k8_secret_provider_class.

- docs/resources/rds_read_replica.md
- duplocloud/resource_duplo_rds_read_replica.go
- duplosdk/rds_instance.go
- Attribute availability_zone added for RDS read replica.
> Attribute availability_zone added for RDS read replica.

- docs/data-sources/ecs_service.md
- docs/data-sources/ecs_services.md
- docs/resources/aws_load_balancer.md
- docs/resources/ecs_service.md
- duplocloud/resource_duplo_kafka_cluster.go
- duplocloud/utils.go
- duplocloud/utils_test.go
Guarantee Sort order for various comma delimited strings related to the Kafka resource.
- plaintextZookeeperConnectString
- plaintextBootstrapBrokerString
- tlsBootstrapBrokerString
Ran `make doc` to generate docs.
> Fix [#1]()
> DUPLO-10298 guarantee broker order

- duplocloud/resource_duplo_kafka_cluster.go
> DUPLO-10400 fixed.

- duplocloud/resource_duplo_aws_dynamodb_table_v2.go
perceiv: fix dyamodb issue, when billing is pay-per-request
> DUPLO-10662 : perceiv: fix dyamodb issue, when billing is pay-per-request

- docs/resources/aws_ssm_parameter.md
- duplocloud/resource_duplo_aws_ssm_parameter.go
- duplosdk/aws_ssm_parameter.go
> Add valid values for the field `type`

- docs/resources/aws_lambda_function.md
- duplocloud/resource_duplo_aws_lambda_function.go
- duplosdk/aws_lambda_function.go
- Attribute tracing_config added in lambda function resource.
> Attribute tracing_config added in lambda function resource.

- docs/resources/asg_profile.md
- docs/resources/aws_host.md
- examples/resources/duplocloud_asg_profile/resource.tf
- examples/resources/duplocloud_aws_host/resource.tf
Add examples for specifying disk size
> add example for updating disk size

- duplocloud/resource_duplo_aws_sqs_queue.go
- duplosdk/aws_sqs.go
Expose Arn for sqs queue resource
> DUPLO-11144 Expose Arn for SQS queue

- duplocloud/resource_duplo_aws_sqs_queue.go
- duplosdk/aws_sqs.go
Add wait logic for Arn on creation
> Fix [#1]()
> DUPLO-11144-arn-wait-logic

- docs/resources/aws_lambda_function.md
- duplocloud/resource_duplo_aws_lambda_function.go
- examples/ephemeral-storage/main.tf
make ephemeral_storage computed; generate docs
[DUPLO-11320](https://app.clickup.com/t/8655600/DUPLO-11320)
[DUPLO-11319](https://app.clickup.com/t/8655600/DUPLO-11319)
> make ephemeral_storage computed; generate docs

- docs/resources/aws_mwaa_environment.md
- duplocloud/resource_duplo_aws_mwaa_environment.go
- examples/resources/duplocloud_aws_mwaa_environment/resource.tf
> DUPLO-11315 mwaa sample doc

- duplosdk/aws_lb_listener_rule.go
Fix to avoid crashing provider when listener rule is not found.
> return error if listener rule not found

- docs/resources/rds_instance.md
- duplocloud/resource_duplo_rds_instance.go
- duplosdk/rds_instance.go
Add support for `storage_type` and `iops`
> add support to storage_type, iops

- docs/resources/s3_bucket.md
- duplocloud/resource_duplo_s3_bucket.go
- duplosdk/tenant_aws_cloud_resources.go
Add computed property DomainName
Testing: TBD
> add DomainName (computed)

- duplocloud/data_source_duplo_tenants.go
- duplocloud/resource_duplo_tenant_secret.go
- duplosdk/tenant.go
1. Update to v3 api which returns a more accurate `status_code` and `message`
2. Remove redundant pointers to slices as they are already passed by reference. This improves readability.
3. Replace empty slice declarations with nil slice declarations.
tested on test19.duplocloud.net with the following resource:
```
resource "duplocloud_tenant" "myapp" {
account_name = "newtenant"
plan_id      = "default"
}
resource "duplocloud_tenant_config" "myapp" {
tenant_id = duplocloud_tenant.myapp.tenant_id
// This turns on a default public access block for S3 buckets.
setting {
key   = "block_public_access_to_s3"
value = "false"
}
// This turns on a default SSL enforcement S3 bucket policy.
setting {
key   = "enforce_ssl_for_s3"
value = "false"
}
}
```
> update v1 -> v3 api

- duplocloud/data_source_duplo_tenant_config.go
> DUPLO-11390 data "duplocloud_tenant-config" fixed

- docs/resources/aws_lambda_permission.md
- docs/resources/infrastructure_setting.md
- examples/resources/duplocloud_aws_lambda_permission/resource.tf
- examples/resources/duplocloud_infrastructure_setting/resource.tf
> more updates

- docs/resources/aws_host.md
- examples/resources/duplocloud_aws_host/resource.tf
> DUPLO-11564 add metadata service option to example

- duplocloud/resource_duplo_rds_instance.go
If the snapshot_id is non-empty, and the password is `donotuse`,  never apply a password change.
> DUPLO-11782

- README.md
- docs/resources/rds_instance.md
- duplocloud/resource_duplo_rds_instance.go
- duplosdk/rds_instance.go
- examples/resources/duplocloud_rds_instance/resource.tf
DUPLO-12128 Add Backup Retention Period. Duplo API uses RDSDBInstance.BackupRetentionPeriod. Api checks if range value is between 0-35.
> DUPLO-12128

- duplocloud/resource_duplo_asg_profile.go
DUPLO-10291  Add ForceNew to true for fullname and new condition for needsResourceAwsASGUpdate.
> DUPLO-10291 Add ForceNew to true for fullname.

- duplocloud/resource_duplo_azure_k8_node_pool.go
- K8s node pool diff issues fixed.
> DUPLO-13530: K8s node pool diff issues fixed.

- duplocloud/resource_duplo_rds_instance.go
DUPLO-13493 Update documentation for backup_retention_period to reflect default and value range.
> DUPLO-13493 Update documentation for backup_retention_period to reflect default and value range.

- docs/resources/rds_instance.md
DUPLO-13493 - update default retention days in the readme doc.
> DUPLO-13493 - update readme default backup retention days.

- duplocloud/resource_duplo_rds_instance.go
- duplosdk/rds_instance.go
DUPLO-13563 - update backup retention to support cluster instances. Refactor  deletion_protection for consistency and reduce number of calls to api.
> DUPLO-13563 - update backup retention to support cluster instances. Refactor  deletion_protection for consistency and reduce number of calls to api. 

- duplocloud/resource_duplo_rds_instance.go
- duplosdk/rds_instance.go
DUPLO-13563 fix BackupRetentionPeriod being passed as 0.
> DUPLO-13563

- duplocloud/data_source_duplo_service.go
- duplocloud/resource_duplo_service.go
- duplosdk/replication_controller.go
> DUPLO-13536 feat: exposes fqdn and related variables for duplo service

- docs/resources/tenant_cleanup_timers.md
- duplocloud/resource_duplo_tenant_cleanup_timers.go
> DUPLO-14087: Add date format

- docs/data-sources/plan_settings.md
- duplocloud/schema_k8s_cron_job_spec_v1beta1.go
> DUPLO-14303: Make cronjob spec.template mutable

- CHANGELOG.md
- duplocloud/resource_duplo_k8_secret.go
Fixed code panic
Fixed Nil map issue
- Map type mismatch fixed
- ...
> DUPLO-11574 Fixed k8 secret bug

- docs/resources/aws_cloudfront_distribution.md
Document format update
- ...
- ...
- ...
> Duplo 15817 doc

- .github/workflows/release-publish.yml
Rotate from @joek-duplo keys to @zafarabbas
> Switch to use new GPG key

- duplocloud/resource_duplo_s3_bucket.go
Fix for Ticket DUPLO-16190 and DUPLO-16191
- Update API fix for enabling public access
- Update API fix for adding default_encryption tag
- ...
> DUPLO-16190 and DUPLO-16191 fix

- .gitignore
- .terraform.tfstate.lock.info
- CHANGELOG.md
- duplocloud/resource_duplo_k8_secret.go
Fixed k8 secret diff issue
Fixed k8 secret diff issue
- fixed DiffSuppressFunc function for secret_data attribute
- ...
- ...
> DUPLO-15935 fixed k8 secret diff issue

- CHANGELOG.md
- duplocloud/resource_duplo_infrastructure.go
Duplo-16551 fixed.
- ...
- ...
- ...
___
enhancement
___
- Enhanced the handling of subnet names in the infrastructure resource for Azure custom prefixes.
- Removed the redundant line that incorrectly set `subnet_fullname` without considering Azure custom prefixes.
- This change ensures that `subnet_fullname` is consistently set, taking into account whether Azure custom prefixes are enabled.
___
<tr>
<td>
<details>
<summary><strong>resource_duplo_infrastructure.go</strong><dd><code>Enhance Azure Subnet Name Handling in Infrastructure Resource</code></dd></summary>
<hr>
duplocloud/resource_duplo_infrastructure.go
<li>Updated …
> Duplo-16551 fixed.

- CHANGELOG.md
- docs/resources/azure_storage_account.md
- docs/resources/infrastructure.md
- duplocloud/resource_duplo_azure_storage_account.go
DUPLO-16461 Fixed
- ...
- ...
- ...
___
___
- Commented out handling and documentation for `account_tier`, `access_tier`, and `enable_https_traffic_only` in Azure Storage Account resource to possibly prevent their usage or to reflect a change in API behavior.
- Disabled the `flattenAzureStorageAccount` function call, which might be part of a larger refactor or due to changes in the underlying API.
- Updated Azure Storage Account and Infrastructure documentation to reflect these changes, including the addition of `subnet_fullname` attribute documentation for Azure infrastructure.
___
<tr>
<td> …
> DUPLO-16461 Fixed

- CHANGELOG.md
- docs/data-sources/gke_credentials.md
- examples/data-sources/duplocloud_gke_credentials/data-source.tf
GKE Document Bug Fix
GKE Document Bug Fix
- Example fix
- ...
- ...
___
documentation, enhancement
___
- Corrected the GKE credentials documentation and Terraform example by updating references from EKS to GKE.
- Updated output values in both documentation and Terraform example to accurately reflect GKE credentials.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
<tr>
<td>
<details>
<summary><strong>gke_credentials.md</strong><dd><code>Fix GKE Credentials Documentation Example</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> DUPLO-16704 FIX GKE DATASOURCE EXAMPLE

- duplosdk/admin.go
HH2 VM bug fix.
- ...
- ...
- ...
> HH2 VM bug fix.

- CHANGELOG.md
- duplocloud/resource_duplo_service.go
- duplosdk/replication_controller.go
DUPLO-15011 DUPLO-16144: TF: Force recreate tf resource when volume mapping is modified for duplo service in terraform (contextual)
- improve - wait delete to complete in tf
- increase sleep to give BE time to cleanup,  before create forcenew
- ...
___
bug_fix, enhancement
___
- Added a new function `ReplicationControllerExists` to efficiently check the existence of a replication controller, streamlining the deletion process.
- Modified the deletion process in `resource_duplo_service.go` to use the new existence check function, ensuring a more reliable deletion.
- Increased the wait time after a service deletion from 40 seconds to 240 seconds to better accommodate backend cleanup processes, particularly for GCP environments.
___
<table><thead><tr><th></th><th …
> DUPLO-15011 DUPLO-16144: TF: Force recreate tf resource when volume mapping is modified for duplo service in terraform (contextual)

- duplocloud/data_source_duplo_eks_credentials.go
- duplocloud/data_source_duplo_gke_credentials.go
Validation removed.
- ...
- ...
- ...
> Validation removed.

- duplocloud/resource_duplo_rds_instance.go
DUPLO-16962 fixed.
- ...
- ...
- ...
> DUPLO-16962 fixed.

- CHANGELOG.md
- duplocloud/resource_duplo_aws_elasticsearch.go
Implemented updation for multi-az for opensearch cluster
- Update functionality enhance to support updation from single to multizone clustering
- ...
- ...
> DUPLO-9155 Update duplocloud TF provider to support create/update  multi AZ Opensearch cluster on AWS

- duplocloud/resource_duplo_ecs_service.go
> Duplo 16595 taskdef bug

- CHANGELOG.md
- build.sh
- docs/resources/admin_system_setting.md
- duplocloud/resource_duplo_admin_system_setting.go
- duplosdk/utils.go
- examples/resources/duplocloud_admin_system_setting/import.sh
DUPLO-11667: TF: duplocloud_admin_system_setting.DBInstanceParameter gives Provider produced inconsistent result after apply error
- Escape '/' in terrform id
- None
___
bug_fix, enhancement
___
- Fixed an issue with handling slashes in `keyType` for resource ID creation and parsing in `duplocloud_admin_system_setting`.
- Added utility functions to encode and decode slashes in identifiers, enhancing the handling of special characters.
- Updated build and import scripts to include documentation generation and guide on handling special characters.
- Updated CHANGELOG and documentation to reflect these changes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td> …
> DUPLO-11667: TF: duplocloud_admin_system_setting.DBInstanceParameter gives Provider produced inconsistent result after apply error

- duplocloud/resource_duplo_aws_dynamodb_table_v2.go
> DUPLO-17203 fixed plugin crash issue on update of globalsecondaryindex

- duplocloud/resource_duplo_aws_dynamodb_table_v2.go
- duplosdk/aws_dynamo_db.go
- ...
- ...
___
enhancement, bug_fix
___
- Added a new function `tagDynamoDBtTableV2` to handle tagging of DynamoDB tables.
- Updated the `resourceAwsDynamoDBTableUpdateV2` function to include tagging and enhanced conditional logic for various table settings like point-in-time recovery and deletion protection.
- Introduced changes to handle deletion protection as a pointer to support conditional updates.
- Implemented new API methods in the SDK for tagging resources and updating SSE specifications and deletion protection settings in isolation, adhering to AWS SDK constraints.
___ …
> Duplo 8942/dynamo table updates

- docs/resources/rds_instance.md
- duplocloud/resource_duplo_rds_instance.go
- duplosdk/rds_instance.go
Added support for `enhanced_monitoring` attribute for `duplocloud_rds_instance` resource 
- Enhanced monitoring support is added for update context
- Document updated
- ...
> DUPLO 9203 Enhance Monitoring

- duplocloud/resource_duplo_gcp_scheduler_job.go
fixed regression issue for `duplocloud_gcp_scheduler_job` resource
- Fixed request assignment for app_engine_target and http_target type resource creation for duplocloud_gcp_scheduler_job
- ...
- ...
> DUPLO 17488 fixed regression issue for duplocloud_gcp_scheduler_job resource

- duplocloud/data_source_duplo_service_lbconfigs.go
- duplocloud/resource_duplo_lbconfigs.go
- duplocloud/utils.go
Fixed case change difference for `protocol` schema attribute for  `duplocloud_duplo_service_lbconfigs` resource
- Added diff suppress function
- ...
- ...
> DUPLO 17149 duplo_service_lbconfigs: terraform shows changes for protocol in plan if deployed with Capital letter protocol

- duplocloud/data_source_duplo_eks_credentials.go
- duplocloud/data_source_duplo_gke_credentials.go
> DUPLO-17629 fixed regression

- docs/resources/rds_instance.md
- duplocloud/resource_duplo_rds_instance.go
- duplosdk/rds_instance.go
Support RDS initial database creation.
- ...
- ...
- ...
> DUPLO-17684 : Support RDS initial database creation.

- duplocloud/resource_duplo_aws_lambda_function.go
New runtime `provided.al2023` added.
- ...
- ...
- ...
> New runtime provided.al2023 added.

- duplosdk/aws_batch.go
Fix resource creation for `duplocloud_aws_batch_compute_environment`
- ...
- ...
- ...
> Compute fix

- duplocloud/resource_duplo_azure_mssql_server.go
- duplocloud/resource_duplo_azure_private_endpoint.go
- duplocloud/resource_duplo_azure_storage_account.go
Azure import resource fixes.
- ...
- ...
- ...
> Azure import resource fixes.

- duplocloud/resource_duplo_plan_kms.go
> Duplo 17881 kms support Plugin crash fix

- duplocloud/resource_duplo_aws_host.go
- duplosdk/native_hosts.go
- examples/resources/duplocloud_aws_host/import.sh
> Duplo 18002 TF: Hosts don't output public ip

- docs/data-sources/duplo_service_lbconfigs.md
- docs/resources/duplo_service_lbconfigs.md
- duplocloud/resource_duplo_lbconfigs.go
- duplosdk/replication_controller.go
New attribute `skip_http_to_https` added.
New attribute `skip_http_to_https` added.
- ...
> New attribute `skip_http_to_https` added.

- duplocloud/resource_duplo_aws_apigateway_event.go
- duplosdk/aws_apigateway_events.go
New attribute api_key_required added.
- New attribute api_key_required added.
- ...
- ...
> New attribute api_key_required added.

- duplocloud/data_source_duplo_k8_secret.go
Masking for non readonly admin resolved
- ...
- ...
- ...
> DUPLO-16746 fixed masking bug

- duplocloud/resource_duplo_aws_host.go
- examples/resources/duplocloud_aws_host/import.sh
Fixed diff issue for metadata
- Added diffsuppress function `diffSuppressWhenExisting` to metadata schema attribute, since `duplocloud_aws_host` does not have update context
- ...
- ...
> Duplo-18507 hybernation reg

- docs/resources/aws_apigateway_event.md
- docs/resources/aws_sns_topic.md
- duplocloud/resource_duplo_aws_sns_topic.go
- duplocloud/utils.go
- duplosdk/aws_sns.go
- examples/resources/duplocloud_aws_sns_topic/resource.tf
Adds support for fifo message processing on duplo's sns topic resources
- Adds a call to get attributes from a topic with retries
- Adds new `fifo_topic` field to sns topic resources
- Enhance example to showcase fifo_topic usage
- Updated provider documentation
QA testing recommended
___
Enhancement, Documentation
___
- Added support for FIFO processing and content-based deduplication for SNS topics.
- Implemented retrieval of SNS topic attributes with retries.
- Extended `DuploSnsTopic` and related structs to include extra attributes.
- Added utility function for dynamic struct field setting.
- Updated documentation to include new fields and enhanced examples.
___ …
> DUPLO-18156 feat: add support for fifo processing for sns topics

- duplocloud/resource_duplo_aws_apigateway_event.go
Patch method added in validation.
- ...
- ...
- ...
> Patch method added in validation.

- duplosdk/admin.go
Custom prefix issue fixed.
- ...
- ...
- ...
> DUPLO-18672: Custom prefix issue fixed.

- duplocloud/resource_duplo_aws_lambda_function.go
- duplosdk/aws_lambda_function.go
Added Wait based on status check after lambda function config update for duplocloud_aws_lambda_function resource
- Added function for lambdaWaitUntilReady
- Added API function for status check
- ...
> DUPLO-19084 TF provider exception on updating lambda function code along with env vars.

- duplocloud/resource_duplo_aws_lambda_function.go
Added lambdaWaitUntilReady to create context
- ...
- ...
- ...
> Duplo 19084 lambda exception

- docs/resources/infrastructure_setting.md
- duplocloud/resource_duplo_infrastructure_setting.go
Added infra settings key which is public and released in documentation for duplocloud_infrastructure_setting
- Updated document
- ...
- ...
> DUPLO-19168 updated infra setting docs

- docs/resources/infrastructure_setting.md
- duplocloud/resource_duplo_infrastructure_setting.go
> Duplo 19168 doc infra setting

- duplocloud/resource_duplo_aws_lambda_function.go
Fixed Error by adding 3 retries on error of status check api to resolve the issue. Which work fine without retries in master version of backend, Issue faced with july 2024 release
- added retyflag of 3 on error to retry
- ...
- ...
> DUPLO-19658 TF provider exception on updating lambda function code along with env vars.

- docs/resources/azure_virtual_machine.md
- duplocloud/resource_duplo_azure_virtual_machine.go
> DUPLO-20437 TF Doc: Fix TF document for azure_virtual_machine resource

- docs/resources/azure_virtual_machine.md
- duplocloud/resource_duplo_azure_virtual_machine.go
> DUPLO-20437 doc fix

- docs/resources/infrastructure_setting.md
- duplocloud/resource_duplo_infrastructure_setting.go
potential fix for doc format issue
- ...
- ...
- ...
> DUPLO-20452 TF:Doc:Infra Settings document format fix in published doc

- .github/workflows/dev-check.yml
- docs/resources/gcp_storage_bucket_v2.md
- duplocloud/diff_utils.go
- duplocloud/resource_duplo_gcp_storage_bucket_v2.go
- examples/resources/duplocloud_gcp_storage_bucket_v2/resource.tf
fixed case sensitive diff issue for location attribute
- Created a diff suppress function ignores case sensitivity for same value
- ...
- ...
> DUPLO-20453 GCP storage bucket Diff issue fix

- docs/resources/aws_batch_compute_environment.md
- duplocloud/resource_duplo_aws_batch_compute_environment.go
Schema attribute update for `duplocloud_aws_batch_compute_environment` resource
- added support of `SPOT_PRICE_CAPACITY_OPTIMIZED` to `allocation_strategy` attribute for `duplocloud_aws_batch_compute_environment` resource
- Updated doc
- ...
> DUPLO-20832 Add support for SPOT_PRICE_CAPACITY_OPTIMIZED in duplocloud_aws_batch_compute_environment

- docs/resources/s3_bucket.md
- duplocloud/resource_duplo_s3_bucket.go
Fix help text per customer feedback
> Fix help text per customer feedback

- duplocloud/resource_duplo_aws_dynamodb_table_v2.go
Tested for july and feb release
- Added check for IsTagsBasedResourceMgmtEnabled
- Kept fallback along with above logic
- ...
> DUPLO-20879 TF Dynamo DB fallback if Get API fails

- duplocloud/resource_duplo_aws_dynamodb_table_v2.go
Added Fallback in read context
- Retry for get api on read context
- ...
- ...
> DUPLO-20879 fallback Dynamo db

- duplocloud/data_source_duplo_k8_secret.go
- duplocloud/data_source_duplo_k8_secrets.go
Added missing data to duplocloud_k8_secrets data sources 
- Initialising missing attribute in k8_secret
- ...
- ...
> DUPLO-18931 Fix secrets missing data

- duplocloud/resource_duplo_aws_ssm_parameter.go
> resolved bug at creation

- CHANGELOG.md
- duplocloud/resource_duplo_azure_k8_node_pool.go
Made priority attribute force new
Made priority attribute force new in duplocloud_azure_k8_node_pool resource
- updated schema attribute priority to forcenew 
- ...
- ...
___
___
- Added `ForceNew: true` to the `priority` attribute in the `duplocloud_azure_k8_node_pool` resource schema to enforce resource recreation when modified.
- Updated the changelog to document this change, improving clarity on resource management updates.
___
<tr>
<td>
<details>
<summary><strong>resource_duplo_azure_k8_node_pool.go</strong><dd><code>Enforce recreation on priority change …
> DUPLO-21060 TF:Azure:AgentPool: Resource 'duplocloud_azure_k8_node_pool' allows update of Scale Set Priority

- CHANGELOG.md
- duplocloud/resource_duplo_asg_profile.go
- ...
- ...
- ...
___
___
- Added validation for the `enabled_metrics` attribute in the Auto Scaling Group profile to ensure only specified metrics are allowed, enhancing configuration accuracy.
- Updated the CHANGELOG to document the enhancement related to the `enabled_metrics` attribute validation.
___
<tr>
<td>
<details>
<summary><strong>resource_duplo_asg_profile.go</strong><dd><code>Add validation for enabled_metrics attribute in ASG profile</code></dd></summary>
<hr>
duplocloud/resource_duplo_asg_profile.go
<li>Added import for …
> DUPLO-19625 added validation to enabled_metrics attribute

- CHANGELOG.md
- duplocloud/resource_duplo_azure_k8_node_pool.go
Added force replacement for availability_zones
Added force replacement for availability_zones in duplocloud_azure_k8_node_pool resource schema
- Added forcenew property for availability_zones attribute
- ...
- ...
___
___
- Added `ForceNew` property to the `availability_zones` attribute in the `duplocloud_azure_k8_node_pool` resource schema to ensure resource replacement when availability zones are updated.
- Updated the changelog to document the addition of the `ForceNew` property and other recent enhancements.
___
<tr>
<td>
<details> …
> DUPLO-21144 TF: duplocloud_azure_k8_node_pool: Updating availability zone should show force replacement of resource in Plan

- CHANGELOG.md
- docs/resources/aws_mwaa_environment.md
- duplocloud/resource_duplo_aws_mwaa_environment.go
DUPLO-21167: add new airflow versions and remove deprecated versions
- add new airflow versions and remove deprecated versions
- add new instance size
- None
___
___
- Added new Airflow versions to the MWAA environment schema and removed deprecated ones.
- Introduced new instance sizes (`mw1.xlarge`, `mw1.2xlarge`) for MWAA environments.
- Updated documentation to reflect changes in instance sizes.
- Updated CHANGELOG to include enhancements and documentation improvements.
___
<tr>
<td>
<details>
<summary><strong>resource_duplo_aws_mwaa_environment.go</strong><dd><code>Update Airflow versions and …
> DUPLO-21167: add new airflow versions and remove deprecated versions

- CHANGELOG.md
- duplocloud/resource_duplo_aws_mwaa_environment.go
DUPLO-21234: mwaa takes long time to delete and create, increase timeout
- increase delete timeout
- none
___
___
- Increased the delete timeout for MWAA environments from 15 to 60 minutes to accommodate longer deletion times.
- Updated the CHANGELOG to reflect the change in delete timeout for MWAA environments.
___
<tr>
<td>
<details>
<summary><strong>resource_duplo_aws_mwaa_environment.go</strong><dd><code>Increase MWAA environment delete timeout to 60 minutes</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
duplocloud/resource_duplo_aws_mwaa_environment.go
<li>Increased the delete timeout for MWAA …
> DUPLO-21234: mwaa takes long time to delete and create, increase timeout

- docs/resources/azure_storageclass_blob.md
- docs/resources/azure_storageclass_queue.md
- docs/resources/azure_storageclass_table.md
- duplocloud/resource_duplo_azure_storage_blob.go
- duplocloud/resource_duplo_azure_storage_queue.go
- duplocloud/resource_duplo_azure_storage_table.go
Removed update context for all storage class resources
Removed update context for duplocloud_azure_storageclass_table, duplocloud_azure_storageclass_queue, duplocloud_azure_storageclass_blob
- Removed update context for duplocloud_azure_storageclass_table, duplocloud_azure_storageclass_blob, duplocloud_azure_storageclass_queue
- ...
- ...
> DUPLO-25423 TF provider: TF plan shows 'update in-place' without updating url in code.

- docs/resources/asg_profile.md
- docs/resources/aws_host.md
- duplocloud/resource_duplo_aws_host.go
ASG profile documentation update
- ...
- ...
- ...
> Duplo 25235 Update doc for duplocloud_asg_profile -> volume

- duplocloud/resource_duplo_azure_storage_blob.go
- duplocloud/resource_duplo_azure_storage_queue.go
- duplocloud/resource_duplo_azure_storage_table.go
Added name validator
Added validation to storage account sub resources duplocloud_azure_storageclass_blob, duplocloud_azure_storageclass_queue, duplocloud_azure_storageclass_table 
- Added validation at schema level
- ...
- ...
> DUPLO-25418 Fixed name validation issue

- duplocloud/data_source_duplo_plan.go
- duplocloud/resource_duplo_aws_ecr_repository.go
- duplocloud/resource_duplo_aws_lambda_function.go
- duplocloud/resource_duplo_gcp_k8_node_pool.go
- duplocloud/resource_duplo_oci_containerengine_node_pool.go
- duplocloud/resource_duplo_plan_kms.go
This pull request addresses issues related to the push lint checks. The changes made ensure that the linting process runs smoothly during push events, helping to maintain code quality and adherence to our coding standards.
- Fixed any identified lint errors in the affected files.
> Fix for Push Lint Checks

- duplocloud/data_source_duplo_asg_profile.go
- duplocloud/resource_duplo_plan_kms_v2.go
- duplocloud/resource_duplo_plan_waf_v2.go
Bug fix asg profile datasource
Typo fix at data duplocloud_asg_profiles
- fixed attribute typo of network_interface and volume
- ...
- ...
> DUPLO-25632 TF:ASG: Terraform plan is failing for duplocloud_asg_profiles (Data Source)

- duplocloud/resource_duplo_s3_replication.go
Fixed s3 bucket validation for tenant
Added custom diff function to validate source bucket
- Created custom diff function that checks does source bucket belongs to tenant on plan 
- ...
- ...
> DUPLO-25458 TF: S3: Replication: Add validation for tenant_id for  source s3 bucket 

- duplocloud/resource_duplo_s3_replication.go
Add validation for rule name for terraform code
- Validation function added which will validate name
> DUPLO-25454: TF: S3: Replication: Add validation for rule name

- duplocloud/resource_duplo_s3_replication.go
Made force new from false to true
- ...
- ...
- ...
> DUPLO-25436 fixed forcenew

- duplocloud/resource_duplo_aws_dynamodb_table_v2.go
DUPLO-25488: dynamo tbl tag based issue (Testing)
- use fullname as table name in duplo crud api
- None
> DUPLO-25488: dynamo tbl tag based issue

- duplocloud/resource_duplo_azure_k8_node_pool.go
- Ticket: `DUPLO-26017`
- Update support added.
- Resource `duplocloud_azure_k8_node_pool` should be able to update FriendlyName, DesiredCapacity, MinSize, MaxSize, EnableAutoScaling
- ...
> DUPLO-26017: Update support added.

- duplocloud/resource_duplo_aws_dynamodb_table_v2.go
DUPLO-25488: fix corner case backword compatibility
- update name only if its "import", for backward compatibility and to skip force recreate.
- ...
> DUPLO-25488: fix corner case backword compatibility (TESTING backword compatibilty)

- docs/resources/k8_ingress.md
- examples/resources/duplocloud_k8_ingress/resource.tf
Updated documentation
- Document updated for duplocloud_k8_ingress
- ...
- ...
> DUPLO-26132 TF:Doc: Fix Ingress TLS Readme- example is partial, was not able to create ingress when followed example

- duplocloud/resource_duplo_k8_ingress.go
Nil pointer exception
Handled nil pointer exception at ob to state converstion for tls in duplocloud_k8_ingress resource
- fixed tls body nil pointer exception
- ...
- ...
> fixed tls regression

- docs/resources/gcp_infra_maintenance_window.md
- duplocloud/resource_duplo_gcp_infra_maintenance_window.go
Fixed exclusion issue and added delete context and changed attribute properties based on it
Fixed exclusion issue and added delete context and changed attribute properties based on it
- Change daily_maintenance_time format validation
- Using post api for delete context
- Changed properties for recurring_window attributes
- updated documentation
- ...
> DUPLO-26393 TF:GKE: Getting error while creating exclusions for resource 'duplocloud_gcp_infra_maintenance_window'

- docs/resources/infrastructure_subnet.md
- duplocloud/resource_duplo_infrastructure_subnet.go
`mysql-flexiserver`, `postgres-flexiserver` added.
- ...
- ...
- ...
> DUPLO-26493: `mysql-flexiserver`, `postgres-flexiserver` added.

- docs/resources/aws_dynamodb_table_v2.md
- examples/resources/duplocloud_aws_dynamodb_table_v2/resource.tf
> DUPLO-26542 Doc:TF:DynamoDb_v2: Correct the usage example provided for ttl

- docs/resources/asg_profile.md
- docs/resources/aws_host.md
- duplocloud/resource_duplo_aws_host.go
> DUPLO-26223 misplaced code repush

- duplocloud/resource_duplo_gcp_infra_maintenance_window.go
Resolving sync issue for duplocloud_gcp_infra_maintenance_window resource
- passing a flag through context to avoid delay on plan phase and to add sleep, before get call
- ...
- ...
> DUPLO-26384 

- docs/resources/azure_availability_set.md
- duplocloud/resource_duplo_azure_availability_set.go
- examples/resources/duplocloud_azure_availability_set/resource.tf
Addeed custom diff to check valid attribute
Updated example
Added check to validate platform_update_domain_count if platform_fault_domain_count is 1
Updated example
- Added custom diff functiom
- Document update
- ...
> DUPLO-26678 , DUPLO-26701

- docs/data-sources/azure_availability_set.md
- duplocloud/data_source_duplo_azure_availability_set.go
- duplocloud/resource_duplo_azure_availability_set.go
- duplosdk/availability_set.go
Added retry on post api for inconsistent error
- updated sku field name in datasource
- added retry at post api
- ...
> DUPLO-26676 TF: Availability Set: Unable to re-create resource in case of update and forces replacement. Getting error - received unexpected response

- duplocloud/data_source_duplo_azure_availability_set.go
Fix for Datasource
fixed error handling for  datasource duplocloud_azure_availability_set
- Fixed error not getting thrown for invalid availability set
- ...
- ...
> DUPLO-26461 TF:GCP:Security Rule: Update of rule_type should show forces replacement

- duplocloud/resource_duplo_gcp_infra_security_rule.go
- duplocloud/resource_duplo_gcp_tenant_security_rule.go
- duplocloud/utils.go
- duplosdk/gcp_security_rule.go
Update logic for waitafterdelete function logic
- Checking fields explicitly for structure is empty if nil interface is not getting resolved
- ...
- ...
> Duplo 26461 TF:GCP:Security Rule: Update of rule_type should show forces replacement

- duplocloud/resource_duplo_infrastructure_onprem.go
Added endpoint validation
Added cluster endpoint validation in duplocloud_infrastructure_onprem
- Added regex validation of valid url
- ...
- [✔︎ ] Manually, on my local system
- ...
> DUPLO-26491 TF:OnPrem infra: Add validation for 'Kubernetes Cluster Endpoint'

- duplocloud/resource_duplo_infrastructure_onprem.go
Regex had issue, Using provider inbuilt url validator
- ...
- ...
- ...
> Duplo 26491

- duplocloud/resource_duplo_azure_virtual_machine.go
Fixed Availablity set id bug
Fixed Availablity set id bug in duplocloud_azure_virtual_machine
- Added whitespace check
- Added diff ignore function if availablity set id case is different
- ...
> DUPLO-26778 Fixed Availablity set id bug

- duplocloud/resource_duplo_azure_datafactory.go
- duplosdk/azure_datafactory.go
fixed public access setting issue
- fixed public access setting issue
- ...
- ...
> DUPLO-26797 Azure>TF- public_access Property in terraform.tfstate file Incorrectly Set to false after being configured as true in main.tf

- duplocloud/resource_duplo_gcp_k8_node_pool.go
replan fix
- handled nil pointer exception
- ...
- ...
> DUPLO-26807 TF: Node Pool: re-plan and apply is failing for resource 'duplocloud_gcp_node_pool (Resource)'

- duplocloud/resource_duplo_s3_bucket.go
Updated timeout for s3 resource
- ...
- ...
- ...
> DUPLO-26723 Creating a S3 bucket using tf timesout and causes state to become inconsistent

- docs/data-sources/asg_profiles.md
- docs/resources/asg_profile.md
- duplocloud/data_source_duplo_asg_profile.go
- duplocloud/resource_duplo_asg_profile.go
- duplosdk/asg.go
updated zone to support multizone for asg profile resource
Depreciated zone to zones for resource duplocloud_asg_profile and handled field in datasource duplocloud_asg_profile.asgtest
- Updated asg profile schema
- Updated Documentation
- ...
> DUPLO-26193 ASG: Support multiple AZs

- docs/data-sources/asg_profiles.md
- duplocloud/resource_duplo_rds_instance.go
- duplosdk/rds_instance.go
Added support to update parmaeter group name for rds resource
Removed no diff effect on parameter group field on change
Updated update context logic to handle paramter group name update request
- Updated update context logic to handle paramter group name update request
- Added sync functionality to sync updated param
- Handled no update error for performance insight if its null
- ...
> Duplo-17163 [TF] Support Parameter group update

- docs/resources/rds_read_replica.md
- duplocloud/resource_duplo_rds_read_replica.go
> DUPLO-29276 Alowing update of db parma for standalone

- .github/workflows/start-hotfix.yml
- start hotfix release workflow added
-  start hotfix release workflow added
- ...
> start hotfix release workflow added

- duplocloud/resource_duplo_gcp_redis_instance.go
> added REDIS_7_0 version

- duplocloud/resource_duplo_rds_instance.go
RDS instance timeout fix
Fixed timeout for resource_duplocloud_rds_instance 
- passing context timout to polling function
- ...
> DUPLO-29354 Timeout fix

- docs/resources/rds_read_replica.md
- duplocloud/resource_duplo_rds_instance.go
- duplocloud/resource_duplo_rds_read_replica.go
RDS Read Replica enhance monitoring support
Added enhance monitoring support for duplocloud_rds_read_replica resource
- Handled updated logic of enhanced monitoring for duplocloud_rds_read_replica resource
- Added custom validation to throw error if enahnced_monitoring specified during creation for both duplocloud_rds_instance and duplocloud_read_replica resource
- Documentation update
- ...
> DUPLO-21294 TF Provider: Add support for `enhanced_monitoring` for `rds_read_replica` resource

- docs/resources/rds_read_replica.md
- duplocloud/resource_duplo_rds_instance.go
- duplocloud/resource_duplo_rds_read_replica.go
Added support for enhanced monitoring in create context for rds related resource
Added support for enhance_monitoring in create context for duplocload_rds_instance and duplocloud_rds_read_replica resource
- Calling update api to set enhanced monitoring in create context 
- Created value based sync function
- Documentation updated
- ...
> DUPLO-29463 TF Provider: Add support for enhanced monitoring in create context for rds instance and rds read replica resource

- docs/resources/s3_bucket_replication.md
- examples/resources/duplocloud_s3_bucket_replication/resource.tf
Updated example for multiple rule creation for a source bucket
- ...
- ...
- ...
> DUPLO-29331 S3 bucket replication documention update

- .github/workflows/finish-hotfix.yml
- .github/workflows/finish-release.yml
- hotfix finish pipeline added.
- ...
- ...
- ...
> Hotfix finish pipeline added.

- duplocloud/resource_duplo_aws_lambda_function_event_config.go
> supporting 0 for max_retry_attempts in duplocloud_aws_lambda_function_event_config

- docs/resources/asg_profile.md
- duplocloud/resource_duplo_asg_profile.go
- duplocloud/resource_duplo_aws_host.go
- duplocloud/utils.go
Validation on zones field
Added validation for not allowing automatic zone to be attached along with zone a and zone b for zones field duplocloud_asg_profile resource
- Added validation logic and diff suppress function
- Documentation update
- ...
> DUPLO-29587 TF:ASG: TF should not allow 'automatic' type of zone along with other zone types

- docs/resources/duplo_service.md
- duplocloud/resource_duplo_service.go
- Doc changes for `agent_platform` attribute.
- ...
- ...
- ...
> Doc changes for `agent_platform` attribute.

- duplosdk/replication_controller.go
> Fix typo for tentantID

- duplocloud/resource_duplo_aws_mwaa_environment.go
See https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-versions.html
- ...
- ...
- ...
> Update Airflow Versions in resource_duplo_aws_mwaa_environment.go

- duplocloud/resource_duplo_aws_mwaa_environment.go
> Fix syntax error

- duplocloud/resource_duplo_gcp_infra_security_rule.go
Difference issue in GCP infra security rule
Fixed diff issue on port field for ports_and_protocols block for duplocloud_gcp_infra_security_rule resource
- Add a suppress diff function to check ports for all and empty which are equivalent
- Added check for ports attribute while setting the field in read context
- ...
> DUPLO-29632 TF:GCP:Security Rule: TF shows update in place for re-plan without any modification

- docs/resources/gcp_infra_security_rule.md
- docs/resources/gcp_tenant_security_rule.md
- docs/resources/k8_helm_repository.md
- duplocloud/resource_duplo_gcp_infra_security_rule.go
- examples/resources/duplocloud_k8_helm_repository/resource.tf
fixed issue when port is all
Restricting value all and empty string for ports field to avoid diff issues
Updated document
- Added validation
- Documentation update
- ...
> DUPLO-29632 Bug Fix

- duplocloud/resource_duplo_aws_dynamodb_table_v2.go
Fixed Plugin crash on GSI removal
Fix for plugin crash when all GSI removed in update context
- Added check on nil pointer
- ...
- ...
> DUPLO-16731 Plugin Crash fix

- docs/resources/infrastructure.md
- duplocloud/resource_duplo_infrastructure.go
- duplocloud/resource_duplo_tenant_secret.go
Regression Fix
Fixed regression for duplocloud_tenant_secret
- Getting name from the response of create api and passing to Get Api change needed due to AWS_SERVICES_TAG_BASED_OWNERSHIP_ENABLED flag change
- Updated documentation for duplocloud_infrastructure
- ...
> DUPLO-29569 [Master/Jan]: TF: Getting error while creating 'duplocloud_tenant_secret'

- duplocloud/resource_duplo_aws_elasticsearch.go
Added support for additional Opensearch non-ebs instances
- ...
- ...
- ...
> DUPLO-29718: Additional Opensearch non-ebs instances

- duplocloud/resource_duplo_aws_elasticsearch.go
Adding changes to hotfix.
- ...
- ...
- ...
> DUPLO-29718: Hotfix: Additional Opensearch non-ebs instances

- duplocloud/resource_duplo_rds_instance.go
Fixed sync on size update
- added polling for size update
- ...
- ...
> DUPLO-29938 [TF] RDS size modification does not wait for sync

- duplocloud/resource_duplo_lbconfigs.go
> Backward compatiblity/lbconfig

- docs/resources/k8s_cron_job.md
- docs/resources/k8s_job.md
- duplocloud/resource_duplo_k8s_cron_job.go
- duplocloud/schema_k8s_pod_spec.go
- duplocloud/structures_k8s_pod.go
> Duplo-29957 Bug Fix for Octa converstion for mode fields

- duplocloud/data_source_duplo_k8s_cron_job.go
- duplocloud/data_source_duplo_k8s_job.go
> DUPLO-29963 Added allocation tag for datasource of duplocloud_k8s_cron_job and duplocloud_k8_cron_job

- duplocloud/resource_duplo_ecache_instance.go
Fix for name length for ecache/redis
Added length validation for ecache resource
- Validating fullname to be maxlength of 40 character
- ...
- ...
> DUPLO-29714 fixed name inconsistency

- duplocloud/resource_duplo_gcp_storage_bucket_v2.go
Fixed import issue for gcp sorage bucket
Fix for bucket import for duplocloud_gcp_storage_bucket_v2 resource
- constructing fullname from name
- ...
- ...
> DUPLO-30168 [TF] GCP Bucket import bug

- docs/resources/asg_profile.md
- duplocloud/resource_duplo_asg_profile.go
fixed doc for zones and handled automatic zones allocation
- Doc updated
- ...
- ...
>  DUPLO-30292 TF: duplocloud_asg_profile zones field doesn't set correctly/match docs

- duplocloud/resource_duplo_ecache_instance.go
[DUPLO-30210] - Added support for valkey cache
- [DUPLO-30210] - Added support for valkey cache
- ...
- ...
> [DUPLO-30210] - Added support for valkey cache

- docs/resources/k8_secret.md
- examples/resources/duplocloud_k8_secret/resource.tf
Documentation Update
Fixed example for duplocloud_k8_secret resource
- example update for k8 secrets resource
- ...
- ...
>   DUPLO-29743 DOC:TF: Correct the usage example for resource 'duplocloud_k8_secret' 

- docs/resources/asg_profile.md
- duplocloud/resource_duplo_asg_profile.go
- duplocloud/utils.go
Fix for no change issue
- Fixed changes not appearing changes done
- Doc update
- ...
> DUPLO-30292

- duplosdk/aws_dynamo_db.go
- duplosdk/client_with_retry_rate_exceeded.go
- duplosdk/ecache_instance.go
- duplosdk/rds_instance.go
Updated RetryAPI
Updated Retry API
Added RetryConf struct and a constructor to update Retry conf for respective API's
- Check for 400 and HRESULT 
- Added Constructor for RetryConf value updation
- Update getapi for RDS and Ecache resource
- ...
> DUPLO-29956 [TF] Update RetryAPI method to retry on 400 and HRESULT

- duplocloud/resource_duplo_asg_profile.go
Updated zone validation and warning message
- updated zone validation and warning message
- ...
- ...
> DUPLO-30378 HotFix for TF support for Asg to support Zones in creating/retrieving ASG profiles.

- docs/resources/asg_profile.md
- duplocloud/resource_duplo_asg_profile.go
Validation change
- Removed automatic logic since it depends on infra setup
- Updated validation and documentation
- [✔︎ ] Manually, on my local system
- ...
> DUPLO-30378 

- duplosdk/client_with_retry_rate_exceeded.go
> DUPLO-29956 Added error handling at leaky place 

- docs/resources/duplo_service_lbconfigs.md
- duplocloud/resource_duplo_lbconfigs.go
> DUPLO-30382 Document update for lbconfigs in duplocloud_duplo_service_lbconfigs resource

- duplocloud/resource_duplo_service.go
- The deletion issue for the init container image attribute is fixed.
- The deletion issue for the init container image attribute is fixed.
- ...
> Duplo 30545:The deletion issue for the init container image attribute is fixed.

- docs/resources/ecache_instance.md
- duplocloud/resource_duplo_ecache_instance.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/go-version/CHANGELOG.md
- vendor/github.com/hashicorp/go-version/LICENSE
- vendor/github.com/hashicorp/go-version/README.md
- vendor/github.com/hashicorp/go-version/constraint.go
- vendor/github.com/hashicorp/go-version/version.go
- vendor/github.com/hashicorp/go-version/version_collection.go
- vendor/modules.txt
Changes made based as discussed for ecache version handling by referring aws resource implementation
- ...
- ...
- ...
> DUPLO-26859

- docs/resources/asg_profile.md
- docs/resources/aws_launch_template.md
- duplocloud/resource_duplo_asg_profile.go
- duplocloud/resource_duplo_aws_launch_template.go
- duplosdk/aws_launch_templates.go
Fix for diff show for resource which dint have zone specified
- zone has default value 0
- zone will be consider only if zones not mentioned
- removed conflicts with zones and zone to use default value
- ...
> DUPLO-30635 [TF] ASG add default value to zone field and manage zones accordingly

- duplocloud/resource_duplo_aws_launch_template.go
- duplosdk/aws_launch_templates.go
> reverting changes not needed

- docs/resources/asg_profile.md
- duplocloud/resource_duplo_asg_profile.go
- examples/resources/duplocloud_asg_profile/resource.tf
> DUPLO-30635 Document fix

- docs/resources/asg_profile.md
- duplocloud/resource_duplo_asg_profile.go
Fixed documentation and reverified backward compatibility  
- ...
- ...
- ...
> DUPLO-30635 Changed zone datatype to string from int

- docs/resources/k8_ingress.md
- duplocloud/resource_duplo_k8_ingress.go
- duplosdk/k8s_ingress.go
- New attribute port_override added
- New attribute port_override added
- ...
> DUPLO-30645 Add support port override in the ingress resource.

- docs/resources/k8_ingress.md
- duplocloud/resource_duplo_k8_ingress.go
Specified port_override support for azure only
- ...
- ...
- ...
> DUPLO-30651 Document updated

- duplocloud/utils.go
- Panic fix for resource duplocloud_tenant_config.
- Panic fix for resource duplocloud_tenant_config.
- ...
> DUPLO-30688: Panic fix for resource duplocloud_tenant_config.

- duplocloud/resource_duplo_aws_launch_template.go
> DUPLO-30293 launch template resource Bug Fix

- duplocloud/resource_duplo_aws_launch_template.go
> DUPLO-30293 bug fix

- docs/resources/k8_helm_repository.md
- duplocloud/resource_duplo_helm_repository.go
> DUPLO-31002 Missing description for default value in type field of Helm Repository resource

- duplocloud/resource_duplo_gcp_sql_database.go
Documentation update
- Documentation update for tier field of duplocloud_gcp_sql_database_instance resource
- ...
- ...
> DUPLO-18349 [TF] Doc:Add support for dedicated Postgresql Node types

- docs/resources/infrastructure.md
- duplocloud/resource_duplo_infrastructure.go
- duplosdk/infrastructure.go
Documentation update
Document update for duplocloud_infrastructure
- Updated description for account_id field
- ...
- ...
> TF Doc: Update infrastructure doc for not adding account id for AWS

- docs/resources/azure_mssqldb_retention_backup.md
- duplocloud/resource_duplo_azure_mssqldb_retention_backup.go
- examples/resources/duplocloud_azure_mssqldb_retention_backup/example.tf
> Duplo 31364 Doc update

- docs/resources/asg_instance_refresh.md
- duplocloud/resource_duplo_asg_instance_refresh.go
Doc Update
Description update for duplocloud_asg_instance_refresh
- ...
- ...
- ...
> DUPLO-31381 TF Doc: Manual instance refresh

- duplocloud/resource_duplo_rds_instance.go
- ForceNew added for attribute `multi_az`
- ForceNew added for attribute `multi_az`
- Backward compatibility
> DUPLO-31394: TF: RDS Not Changing to Multi AZ when selected.

- docs/resources/asg_instance_refresh.md
- duplocloud/resource_duplo_asg_instance_refresh.go
> Duplo 31381 Doc updated

- duplocloud/resource_duplo_k8s_cron_job.go
> DUPLO-31028 Bug fix

- duplocloud/resource_duplo_aws_sqs_queue.go
Validation Fix 
Validation fix based on queue type 
- Added validation for fields that are applicable when queue is fifo
- ...
- ...
> DUPLO-31074 TF: SQS Queue Object changes after creation

- duplocloud/resource_duplo_aws_sqs_queue.go
SQS arn not getting set on update fix
- Polling till arn is available
- ...
- ...
> DUPLO-31439 TF: SQS Queue Object changes after creation

- duplocloud/resource_duplo_azure_postgresql_database.go
Deprecated duplocloud_azure_postgresql_database resource
- Added deprecate message to duplocloud_azure_postgresql_database resource
- ...
- ...
> DUPLO-31511 TF Deprecate duplocloud_azure_postgresql_database resource

- docs/resources/azure_tenant_key_vault_secret.md
- duplocloud/resource_duplo_azure_tenant_key_vault_secret.go
- duplosdk/azure_key_vault.go
Support for editing azure vault secret
Added update context for duplocloud_azure_tenant_key_vault_secret resource
- Added update context logic to update key vault secret
- Update fields attribute and updated doc
- ...
> DUPLO-31499 Azure Keyvault edit secret feature with Duplo TF provider

- docs/resources/tenant_network_security_rule.md
- examples/resources/duplocloud_tenant_network_security_rule/import.sh
Document fix
Updated import.sh file for duplocloud_tenant_network_security_rule resource
- Added usage comment to import file
- Document updated
- ...
> DUPLO-31439  DOC: duplocloud_tenant_network_security_rule Needs example for IP-based Import

- duplocloud/resource_duplo_gcp_k8_node_pool.go
Node count update fix
Fixed autoscaling related update issues
- Fixed autoscaling related update issues
- Added custom validation
- Added polling function
- Calling read context from update context to set tf state
- ...
> DUPLO-31506 TF: GCP NodePools not updating when changed in TF code

- docs/resources/asg_instance_refresh.md
- duplocloud/resource_duplo_asg_instance_refresh.go
> ASG Instance refresh doc update

- duplocloud/resource_duplo_infrastructure.go
Fixed wait_until_deleted field value initialisation
Removed diff suppress function
- Removed diff suppress function on wait_until_deleted
- Handled nil pointer exception on data source
- ...
> DUPLO-31538 [TF] Infrastructure resource should wait till destroy of infra resource if wait_until_deleted is true

- duplosdk/aws_launch_templates.go
Unmarshall fix
Fixed unmarshalling issue for duplocloud_aws_launch_template  resource
- Multiple field definition updated for response model 
- ...
- ...
> DUPLO-31781 TF: 0.11.8 Creating ASG with spot instances breaks completely

- duplocloud/resource_duplo_tenant.go
-  Case insensitive check added for validation.
- Prefix validation.
- Already exist check.
> DUPLO-31935: Case insensitive check added for validation.

- duplocloud/resource_duplo_aws_cloudwatch_metric_alarm.go
- duplosdk/aws_cloudwatch.go
Fix for name
Added base64 encoding for name while fetching alarm
- base64 converstion on fullname
- ...
- ...
> DUPLO-32684 Instance alarms url needs updating

- duplocloud/resource_duplo_ecs_task_definition.go
Updated error formating
- ...
- ...
- ...
> DUPLO-32611

- docs/resources/azure_cosmos_db_account.md
- docs/resources/azure_cosmos_db_container.md
- docs/resources/azure_cosmos_db_database.md
- duplocloud/resource_duplo_aws_lambda_function_event_config.go
- duplocloud/resource_duplo_azure_cosmos_db.go
- duplocloud/resource_duplo_azure_cosmos_db_account.go
- duplocloud/resource_duplo_azure_cosmos_db_container.go
Bug fix
Typo fix
- Fixed typo in customise diff function
- ...
- ...
> DUPLO-32692 TF: Cosmos DB: Account: TF shows update-in-place on 'max_staleness_prefix' for resource 'duplocloud_azure_cosmos_db_account'

- duplocloud/resource_duplo_ecs_task_definition.go
- duplosdk/ecs_task_def.go
Set Comparabilities
Fix for setting Comparabilities if not set
- Field change in Get api's for required_compati
- Handled other dangling field
- ...
> DUPLO-32755 Terraform ECS task definition fails with "bridge" network mode

- docs/data-sources/ecs_task_definition.md
- docs/resources/ecs_task_definition.md
- duplocloud/resource_duplo_ecs_task_definition.go
Removed validation on the field requires_compatibilities
- Description update
- Removed validation
- ...
> DUPLO-32755 

- duplocloud/resource_duplo_ecs_task_definition.go
Added diff suppress on update. duplocloud_ecs_task_definition resource do not have update context
- ...
- ...
- ...
> DUPLO-32755

- duplocloud/resource_duplo_tenant_config.go
Plugin crash fix
Edge case, plugin crash on destroy interrupt and redestroying resource duplocloud_tenant_config
- added a nil check before converting interface to desired type
- ...
- ...
> DUPLO-35582 TF: Tenant Config crashes plugin when destroy attempt is cancelled and re destroy is performed

- duplocloud/resource_duplo_plan_settings.go
Added validation for other get api and put api inside delete context
- ...
- ...
- ...
> DUPLO-35597 Bugfix

- duplocloud/resource_duplo_k8_ingress.go
Bug fix on ingress resource for certificate_arn and certificate_arns
- manage the usage
- ...
- ...
> DUPLO-35606 DUPLO-35607 DUPLO-35608

- duplosdk/user.go
API change
API change for duplo_user_tenant_access resource
- Added query parameter to allow deletion of admin access from a tenant
- ...
- ...
> DUPLO-35660 [TF] Implement Get API changes for user tenant access

- docs/resources/azure_postgresql_flexible_database_v2.md
- docs/resources/azure_postgresql_flexible_db_ad_administrator.md
- duplocloud/resource_duplo_azure_postgresql_flexible_database_active_directory_administrator.go
- duplosdk/azure_postgresql_database.go
- examples/resources/duplocloud_azure_postgresql_flexible_database_v2/resource.tf
- examples/resources/duplocloud_azure_postgresql_flexible_db_ad_administrator/resource.tf
Handled azure halt on process by introducing polling function to ensure delete
- ...
- ...
- ...
> DUPLO-35511 Fixed Multi delete issue

- docs/resources/infrastructure_subnet.md
- examples/resources/duplocloud_infrastructure_subnet/resource.tf
> DUPLO-35203 Doc fix

- docs/resources/aws_load_balancer_listener.md
- docs/resources/ecache_instance.md
- duplocloud/resource_duplo_ecache_instance.go
- duplocloud/resource_duplo_tenant_aws_lb_listeners.go
- duplosdk/ecache_instance.go
- duplosdk/tenant_aws_cloud_resources.go
- examples/resources/duplocloud_aws_load_balancer_listener/resource.tf
Extended support
Support for fixed_response and redirect default actions for duplocloud_aws_load_balancer_listener
- Changed schema definition
- Handled Backward compatiability
- Updated document
- ...
> DUPLO-9157 Update duplocloud TF provider to add default action in ALB listener rules

- duplocloud/resource_duplo_ecs_task_definition.go
Fix for diff on container_definition field
Setting container_definition field so diff doesnt occur for duplocloud_ecs_task_definition resource
- Comparing container_definition as string based on equal fold if there is difference from response attaching user input definition. If during import container_definition is not there attaching response value. It is possible container_definition can have additional settings added external to terraform
- Logically handling family name discrepancy based on duploservice prefix attachments
- ...
> DUPLO-36803 TF: Task definition is being forcefully replaced during imported Terraform code plan

- duplocloud/duplocloud_ecache_associate_global_secondary_cluster.go
- duplocloud/resource_duplo_ecache_global_datastore.go
> DUPLO-35622

- duplocloud/duplocloud_ecache_associate_global_secondary_cluster.go
- duplocloud/resource_duplo_ecache_global_datastore.go
> DUPLO-35622 fixed default timeout issue

- docs/resources/ecache_associate_global_secondary_cluster.md
- duplocloud/resource_duplo_asg_profile.go
- examples/resources/duplocloud_ecache_associate_global_secondary_cluster/resource.tf
removed timestamp from asg and added validation
- Added validation to check if same name already exist and not allowing asg to create. This happens when create_before_destory is true
- Removed timestamp getting append to asg
- ...
> TF Remove timestamp suffix from ASG and add validation to check if same name asg exist

- duplocloud/data_source_duplo_infrastructure.go
- duplocloud/resource_duplo_infrastructure.go
Bug fix
On import setting field not getting set
- added context value to differentiate import flow and normal flow
- filtering setting value 
- ...
> DUPLO-37205 TF: Setting field not getting set on import for Infrastructure resource

- docs/resources/aws_dynamodb_table_v2.md
- duplocloud/resource_duplo_aws_dynamodb_table_v2.go
Potential fix
- removed tag from dynamo and fixed mapping
- ...
- ...
> DUPLO-33015 Can't import and then manage dynamo db tables with Terraform

- docs/resources/aws_rds_global_secondary.md
- duplocloud/resource_duplo_aws_rds_global_database.go
Missing change pushed again
- ...
- ...
- ...
> DUPLO-37376

- docs/resources/gcp_sql_database_instance.md
- duplocloud/resource_duplo_gcp_sql_database.go
> potential fix

- docs/resources/gcp_sql_database_instance.md
- duplocloud/resource_duplo_aws_cloudwatch_event_target.go
- duplocloud/resource_duplo_gcp_sql_database.go
- duplosdk/gcp_sql_database.go
> Cherrypicked commit to merge into hotfix/0.11.27
